<?php

namespace Database\Seeders;
use App\Models\Municipio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => 1, 'nombre' => 'LETICIA', 'departamento_id' => 1],
            ['id' => 2, 'nombre' => 'PUERTO NARIÑO', 'departamento_id' => 1],
            ['id' => 3, 'nombre' => 'MEDELLIN', 'departamento_id' => 2],
            ['id' => 4, 'nombre' => 'ABEJORRAL', 'departamento_id' => 2],
            ['id' => 5, 'nombre' => 'ABRIAQUI', 'departamento_id' => 2],
            ['id' => 6, 'nombre' => 'ALEJANDRIA ', 'departamento_id' => 2],
            ['id' => 7, 'nombre' => 'AMAGA', 'departamento_id' => 2],
            ['id' => 8, 'nombre' => 'AMALFI', 'departamento_id' => 2],
            ['id' => 9, 'nombre' => 'ANDES', 'departamento_id' => 2],
            ['id' => 10, 'nombre' => 'ANGELOPOLIS', 'departamento_id' => 2],
            ['id' => 11, 'nombre' => 'ANGOSTURA', 'departamento_id' => 2],
            ['id' => 12, 'nombre' => 'ANORI', 'departamento_id' => 2],
            ['id' => 13, 'nombre' => 'SANTA FE DE ANTIOQUIA', 'departamento_id' => 2],
            ['id' => 14, 'nombre' => 'ANZA     ', 'departamento_id' => 2],
            ['id' => 15, 'nombre' => 'APARTADO', 'departamento_id' => 2],
            ['id' => 16, 'nombre' => 'ARBOLETES', 'departamento_id' => 2],
            ['id' => 17, 'nombre' => 'ARGELIA', 'departamento_id' => 2],
            ['id' => 18, 'nombre' => 'ARMENIA', 'departamento_id' => 2],
            ['id' => 19, 'nombre' => 'BARBOSA    ', 'departamento_id' => 2],
            ['id' => 20, 'nombre' => 'BELMIRA', 'departamento_id' => 2],
            ['id' => 21, 'nombre' => 'BELLO', 'departamento_id' => 2],
            ['id' => 22, 'nombre' => 'BETANIA', 'departamento_id' => 2],
            ['id' => 23, 'nombre' => 'BETULIA', 'departamento_id' => 2],
            ['id' => 24, 'nombre' => 'CIUDAD BOLIVAR', 'departamento_id' => 2],
            ['id' => 25, 'nombre' => 'BRICEÑO', 'departamento_id' => 2],
            ['id' => 26, 'nombre' => 'BURITICA', 'departamento_id' => 2],
            ['id' => 27, 'nombre' => 'CACERES', 'departamento_id' => 2],
            ['id' => 28, 'nombre' => 'CAICEDO', 'departamento_id' => 2],
            ['id' => 29, 'nombre' => 'CALDAS', 'departamento_id' => 2],
            ['id' => 30, 'nombre' => 'CAMPAMENTO', 'departamento_id' => 2],
            ['id' => 31, 'nombre' => 'CAÑASGORDAS', 'departamento_id' => 2],
            ['id' => 32, 'nombre' => 'CARACOLI ', 'departamento_id' => 2],
            ['id' => 33, 'nombre' => 'CARAMANTA ', 'departamento_id' => 2],
            ['id' => 34, 'nombre' => 'CAREPA', 'departamento_id' => 2],
            ['id' => 35, 'nombre' => 'CARMEN DE VIBORAL', 'departamento_id' => 2],
            ['id' => 36, 'nombre' => 'CAROLINA DEL PRINCIPE', 'departamento_id' => 2],
            ['id' => 37, 'nombre' => 'CAUCASIA', 'departamento_id' => 2],
            ['id' => 38, 'nombre' => 'CHIGORODO', 'departamento_id' => 2],
            ['id' => 39, 'nombre' => 'CISNEROS', 'departamento_id' => 2],
            ['id' => 40, 'nombre' => 'COCORNA', 'departamento_id' => 2],
            ['id' => 41, 'nombre' => 'CONCEPCION ', 'departamento_id' => 2],
            ['id' => 42, 'nombre' => 'CONCORDIA ', 'departamento_id' => 2],
            ['id' => 43, 'nombre' => 'COPACABANA', 'departamento_id' => 2],
            ['id' => 44, 'nombre' => 'DABEIBA', 'departamento_id' => 2],
            ['id' => 45, 'nombre' => 'DON MATIAS    ', 'departamento_id' => 2],
            ['id' => 46, 'nombre' => 'EBEJICO', 'departamento_id' => 2],
            ['id' => 47, 'nombre' => 'EL BAGRE', 'departamento_id' => 2],
            ['id' => 48, 'nombre' => 'ENTRERRIOS', 'departamento_id' => 2],
            ['id' => 49, 'nombre' => 'ENVIGADO ', 'departamento_id' => 2],
            ['id' => 50, 'nombre' => 'FREDONIA    ', 'departamento_id' => 2],
            ['id' => 51, 'nombre' => 'FRONTINO ', 'departamento_id' => 2],
            ['id' => 52, 'nombre' => 'GIRALDO', 'departamento_id' => 2],
            ['id' => 53, 'nombre' => 'GIRARDOTA   ', 'departamento_id' => 2],
            ['id' => 54, 'nombre' => 'GOMEZ PLATA', 'departamento_id' => 2],
            ['id' => 55, 'nombre' => 'GRANADA', 'departamento_id' => 2],
            ['id' => 56, 'nombre' => 'GUADALUPE', 'departamento_id' => 2],
            ['id' => 57, 'nombre' => 'GUARNE   ', 'departamento_id' => 2],
            ['id' => 58, 'nombre' => 'GUATAPE', 'departamento_id' => 2],
            ['id' => 59, 'nombre' => 'HELICONIA   ', 'departamento_id' => 2],
            ['id' => 60, 'nombre' => 'HISPANIA    ', 'departamento_id' => 2],
            ['id' => 61, 'nombre' => 'ITAGUI', 'departamento_id' => 2],
            ['id' => 62, 'nombre' => 'ITUANGO', 'departamento_id' => 2],
            ['id' => 63, 'nombre' => 'JARDIN', 'departamento_id' => 2],
            ['id' => 64, 'nombre' => 'JERICO', 'departamento_id' => 2],
            ['id' => 65, 'nombre' => 'LA CEJA', 'departamento_id' => 2],
            ['id' => 66, 'nombre' => 'LA ESTRELLA ', 'departamento_id' => 2],
            ['id' => 67, 'nombre' => 'LA PINTADA', 'departamento_id' => 2],
            ['id' => 68, 'nombre' => 'LA UNION ', 'departamento_id' => 2],
            ['id' => 69, 'nombre' => 'LIBORINA', 'departamento_id' => 2],
            ['id' => 70, 'nombre' => 'MACEO  ', 'departamento_id' => 2],
            ['id' => 71, 'nombre' => 'MARINILLA', 'departamento_id' => 2],
            ['id' => 72, 'nombre' => 'MONTEBELLO', 'departamento_id' => 2],
            ['id' => 73, 'nombre' => 'MURINDO', 'departamento_id' => 2],
            ['id' => 74, 'nombre' => 'MUTATA', 'departamento_id' => 2],
            ['id' => 75, 'nombre' => 'NARIÑO', 'departamento_id' => 2],
            ['id' => 76, 'nombre' => 'NECOCLI', 'departamento_id' => 2],
            ['id' => 77, 'nombre' => 'NECHI', 'departamento_id' => 2],
            ['id' => 78, 'nombre' => 'OLAYA', 'departamento_id' => 2],
            ['id' => 79, 'nombre' => 'PEÑOL', 'departamento_id' => 2],
            ['id' => 80, 'nombre' => 'PEQUE', 'departamento_id' => 2],
            ['id' => 81, 'nombre' => 'PUEBLORRICO', 'departamento_id' => 2],
            ['id' => 82, 'nombre' => 'PUERTO BERRIO', 'departamento_id' => 2],
            ['id' => 83, 'nombre' => 'PUERTO NARE (LA MAGDALENA) *', 'departamento_id' => 2],
            ['id' => 84, 'nombre' => 'PUERTO TRIUNFO', 'departamento_id' => 2],
            ['id' => 85, 'nombre' => 'REMEDIOS    ', 'departamento_id' => 2],
            ['id' => 86, 'nombre' => 'RETIRO ', 'departamento_id' => 2],
            ['id' => 87, 'nombre' => 'RIONEGRO', 'departamento_id' => 2],
            ['id' => 88, 'nombre' => 'SABANALARGA   ', 'departamento_id' => 2],
            ['id' => 89, 'nombre' => 'SABANETA', 'departamento_id' => 2],
            ['id' => 90, 'nombre' => 'SALGAR ', 'departamento_id' => 2],
            ['id' => 91, 'nombre' => 'SAN ANDRES', 'departamento_id' => 2],
            ['id' => 92, 'nombre' => 'SAN CARLOS', 'departamento_id' => 2],
            ['id' => 93, 'nombre' => 'SAN FRANCISCO', 'departamento_id' => 2],
            ['id' => 94, 'nombre' => 'SAN JERONIMO', 'departamento_id' => 2],
            ['id' => 95, 'nombre' => 'SAN JOSE DE LA MONTAÑA', 'departamento_id' => 2],
            ['id' => 96, 'nombre' => 'SAN JUAN DE URABA', 'departamento_id' => 2],
            ['id' => 97, 'nombre' => 'SAN LUIS', 'departamento_id' => 2],
            ['id' => 98, 'nombre' => 'SAN PEDRO', 'departamento_id' => 2],
            ['id' => 99, 'nombre' => 'SAN PEDRO DE URABA   ', 'departamento_id' => 2],
            ['id' => 100, 'nombre' => 'SAN RAFAEL    ', 'departamento_id' => 2],
            ['id' => 101, 'nombre' => 'SAN ROQUE', 'departamento_id' => 2],
            ['id' => 102, 'nombre' => 'SAN VICENTE', 'departamento_id' => 2],
            ['id' => 103, 'nombre' => 'SANTA BARBARA', 'departamento_id' => 2],
            ['id' => 104, 'nombre' => 'SANTA ROSA DE OSOS', 'departamento_id' => 2],
            ['id' => 105, 'nombre' => 'SANTO DOMINGO', 'departamento_id' => 2],
            ['id' => 106, 'nombre' => 'EL SANTUARIO', 'departamento_id' => 2],
            ['id' => 107, 'nombre' => 'SEGOVIA', 'departamento_id' => 2],
            ['id' => 108, 'nombre' => 'SONSON', 'departamento_id' => 2],
            ['id' => 109, 'nombre' => 'SOPETRAN', 'departamento_id' => 2],
            ['id' => 110, 'nombre' => 'TAMESIS', 'departamento_id' => 2],
            ['id' => 111, 'nombre' => 'TARAZA', 'departamento_id' => 2],
            ['id' => 112, 'nombre' => 'TARSO', 'departamento_id' => 2],
            ['id' => 113, 'nombre' => 'TITIRIBI', 'departamento_id' => 2],
            ['id' => 114, 'nombre' => 'TOLEDO ', 'departamento_id' => 2],
            ['id' => 115, 'nombre' => 'TURBO', 'departamento_id' => 2],
            ['id' => 116, 'nombre' => 'URAMITA', 'departamento_id' => 2],
            ['id' => 117, 'nombre' => 'URRAO', 'departamento_id' => 2],
            ['id' => 118, 'nombre' => 'VALDIVIA', 'departamento_id' => 2],
            ['id' => 119, 'nombre' => 'VALPARAISO ', 'departamento_id' => 2],
            ['id' => 120, 'nombre' => 'VEGACHI', 'departamento_id' => 2],
            ['id' => 121, 'nombre' => 'VENECIA', 'departamento_id' => 2],
            ['id' => 122, 'nombre' => 'VIGIA DEL FUERTE', 'departamento_id' => 2],
            ['id' => 123, 'nombre' => 'YALI    ', 'departamento_id' => 2],
            ['id' => 124, 'nombre' => 'YARUMAL    ', 'departamento_id' => 2],
            ['id' => 125, 'nombre' => 'YOLOMBO   ', 'departamento_id' => 2],
            ['id' => 126, 'nombre' => 'YONDÓ (CASABE)', 'departamento_id' => 2],
            ['id' => 127, 'nombre' => 'ZARAGOZA', 'departamento_id' => 2],
            ['id' => 128, 'nombre' => 'ARAUCA', 'departamento_id' => 3],
            ['id' => 129, 'nombre' => 'ARAUQUITA', 'departamento_id' => 3],
            ['id' => 130, 'nombre' => 'CRAVO NORTE', 'departamento_id' => 3],
            ['id' => 131, 'nombre' => 'FORTUL     ', 'departamento_id' => 3],
            ['id' => 132, 'nombre' => 'PUERTO RONDON ', 'departamento_id' => 3],
            ['id' => 133, 'nombre' => 'SARAVENA', 'departamento_id' => 3],
            ['id' => 134, 'nombre' => 'TAME', 'departamento_id' => 3],
            ['id' => 135, 'nombre' => 'PROVIDENCIA', 'departamento_id' => 4],
            ['id' => 136, 'nombre' => 'BARRANQUILLA, DISTRITO ESP, INDUSTRIAL Y PORTUARIO', 'departamento_id' => 5],
            ['id' => 137, 'nombre' => 'BARANOA', 'departamento_id' => 5],
            ['id' => 138, 'nombre' => 'CAMPO DE LA CRUZ', 'departamento_id' => 5],
            ['id' => 139, 'nombre' => 'CANDELARIA', 'departamento_id' => 5],
            ['id' => 140, 'nombre' => 'GALAPA   ', 'departamento_id' => 5],
            ['id' => 141, 'nombre' => 'JUAN DE ACOSTA', 'departamento_id' => 5],
            ['id' => 142, 'nombre' => 'LURUACO', 'departamento_id' => 5],
            ['id' => 143, 'nombre' => 'MALAMBO', 'departamento_id' => 5],
            ['id' => 144, 'nombre' => 'MANATI', 'departamento_id' => 5],
            ['id' => 145, 'nombre' => 'PALMAR DE VARELA', 'departamento_id' => 5],
            ['id' => 146, 'nombre' => 'PIOJO', 'departamento_id' => 5],
            ['id' => 147, 'nombre' => 'POLO NUEVO    ', 'departamento_id' => 5],
            ['id' => 148, 'nombre' => 'PONEDERA', 'departamento_id' => 5],
            ['id' => 149, 'nombre' => 'PUERTO COLOMBIA', 'departamento_id' => 5],
            ['id' => 150, 'nombre' => 'REPELON', 'departamento_id' => 5],
            ['id' => 151, 'nombre' => 'SABANAGRANDE', 'departamento_id' => 5],
            ['id' => 152, 'nombre' => 'SABANALARGA', 'departamento_id' => 5],
            ['id' => 153, 'nombre' => 'SANTA LUCIA', 'departamento_id' => 5],
            ['id' => 154, 'nombre' => 'SANTO TOMAS', 'departamento_id' => 5],
            ['id' => 155, 'nombre' => 'SOLEDAD', 'departamento_id' => 5],
            ['id' => 156, 'nombre' => 'SUAN', 'departamento_id' => 5],
            ['id' => 157, 'nombre' => 'TUBARA ', 'departamento_id' => 5],
            ['id' => 158, 'nombre' => 'USIACURI', 'departamento_id' => 5],
            ['id' => 159, 'nombre' => 'CARTAGENA DE INDIAS, DISTRITO TURISTICO Y CULTURAL', 'departamento_id' => 6],
            ['id' => 160, 'nombre' => 'ACHI', 'departamento_id' => 6],
            ['id' => 161, 'nombre' => 'ALTOS DEL ROSARIO', 'departamento_id' => 6],
            ['id' => 162, 'nombre' => 'ARENAL', 'departamento_id' => 6],
            ['id' => 163, 'nombre' => 'ARJONA', 'departamento_id' => 6],
            ['id' => 164, 'nombre' => 'ARROYOHONDO', 'departamento_id' => 6],
            ['id' => 165, 'nombre' => 'BARRANCO DE LOBA', 'departamento_id' => 6],
            ['id' => 166, 'nombre' => 'CALAMAR', 'departamento_id' => 6],
            ['id' => 167, 'nombre' => 'CANTAGALLO', 'departamento_id' => 6],
            ['id' => 168, 'nombre' => 'CICUCO', 'departamento_id' => 6],
            ['id' => 169, 'nombre' => 'CORDOBA', 'departamento_id' => 6],
            ['id' => 170, 'nombre' => 'CLEMENCIA', 'departamento_id' => 6],
            ['id' => 171, 'nombre' => 'EL CARMEN DE BOLIVAR', 'departamento_id' => 6],
            ['id' => 172, 'nombre' => 'EL GUAMO', 'departamento_id' => 6],
            ['id' => 173, 'nombre' => 'EL PEÑON', 'departamento_id' => 6],
            ['id' => 174, 'nombre' => 'HATILLO DE LOBA', 'departamento_id' => 6],
            ['id' => 175, 'nombre' => 'MAGANGUE', 'departamento_id' => 6],
            ['id' => 176, 'nombre' => 'MAHATES', 'departamento_id' => 6],
            ['id' => 177, 'nombre' => 'MARGARITA', 'departamento_id' => 6],
            ['id' => 178, 'nombre' => 'MARIA LA BAJA', 'departamento_id' => 6],
            ['id' => 179, 'nombre' => 'MONTECRISTO', 'departamento_id' => 6],
            ['id' => 180, 'nombre' => 'SANTA CRUZ DE MOMPÓX', 'departamento_id' => 6],
            ['id' => 181, 'nombre' => 'MORALES', 'departamento_id' => 6],
            ['id' => 182, 'nombre' => 'NOROSÍ *', 'departamento_id' => 6],
            ['id' => 183, 'nombre' => 'PINILLOS', 'departamento_id' => 6],
            ['id' => 184, 'nombre' => 'REGIDOR', 'departamento_id' => 6],
            ['id' => 185, 'nombre' => 'RIO VIEJO', 'departamento_id' => 6],
            ['id' => 186, 'nombre' => 'SAN CRISTOBAL', 'departamento_id' => 6],
            ['id' => 187, 'nombre' => 'SAN ESTANISLAO', 'departamento_id' => 6],
            ['id' => 188, 'nombre' => 'SAN FERNANDO', 'departamento_id' => 6],
            ['id' => 189, 'nombre' => 'SAN JACINTO', 'departamento_id' => 6],
            ['id' => 190, 'nombre' => 'SAN JACINTO DEL CAUCA', 'departamento_id' => 6],
            ['id' => 191, 'nombre' => 'SAN JUAN NEPOMUCENO', 'departamento_id' => 6],
            ['id' => 192, 'nombre' => 'SAN MARTIN DE LOBA', 'departamento_id' => 6],
            ['id' => 193, 'nombre' => 'SAN PABLO', 'departamento_id' => 6],
            ['id' => 194, 'nombre' => 'SANTA CATALINA', 'departamento_id' => 6],
            ['id' => 195, 'nombre' => 'SANTA ROSA', 'departamento_id' => 6],
            ['id' => 196, 'nombre' => 'SANTA ROSA DEL SUR', 'departamento_id' => 6],
            ['id' => 197, 'nombre' => 'SIMITI', 'departamento_id' => 6],
            ['id' => 198, 'nombre' => 'SOPLAVIENTO', 'departamento_id' => 6],
            ['id' => 199, 'nombre' => 'TALAIGUA NUEVO', 'departamento_id' => 6],
            ['id' => 200, 'nombre' => 'TIQUISIO', 'departamento_id' => 6],
            ['id' => 201, 'nombre' => 'TURBACO', 'departamento_id' => 6],
            ['id' => 202, 'nombre' => 'TURBANA', 'departamento_id' => 6],
            ['id' => 203, 'nombre' => 'VILLANUEVA', 'departamento_id' => 6],
            ['id' => 204, 'nombre' => 'ZAMBRANO', 'departamento_id' => 6],
            ['id' => 205, 'nombre' => 'TUNJA ', 'departamento_id' => 7],
            ['id' => 206, 'nombre' => 'ALMEIDA', 'departamento_id' => 7],
            ['id' => 207, 'nombre' => 'AQUITANIA', 'departamento_id' => 7],
            ['id' => 208, 'nombre' => 'ARCABUCO', 'departamento_id' => 7],
            ['id' => 209, 'nombre' => 'BELEN ', 'departamento_id' => 7],
            ['id' => 210, 'nombre' => 'BERBEO', 'departamento_id' => 7],
            ['id' => 211, 'nombre' => 'BETEITIVA   ', 'departamento_id' => 7],
            ['id' => 212, 'nombre' => 'BOAVITA', 'departamento_id' => 7],
            ['id' => 213, 'nombre' => 'BOYACA  ', 'departamento_id' => 7],
            ['id' => 214, 'nombre' => 'BRICEÑO', 'departamento_id' => 7],
            ['id' => 215, 'nombre' => 'BUENAVISTA', 'departamento_id' => 7],
            ['id' => 216, 'nombre' => 'BUSBANZA ', 'departamento_id' => 7],
            ['id' => 217, 'nombre' => 'CALDAS ', 'departamento_id' => 7],
            ['id' => 218, 'nombre' => 'CAMPOHERMOSO', 'departamento_id' => 7],
            ['id' => 219, 'nombre' => 'CERINZA', 'departamento_id' => 7],
            ['id' => 220, 'nombre' => 'CHINAVITA', 'departamento_id' => 7],
            ['id' => 221, 'nombre' => 'CHIQUINQUIRA ', 'departamento_id' => 7],
            ['id' => 222, 'nombre' => 'CHISCAS ', 'departamento_id' => 7],
            ['id' => 223, 'nombre' => 'CHITA', 'departamento_id' => 7],
            ['id' => 224, 'nombre' => 'CHITARAQUE', 'departamento_id' => 7],
            ['id' => 225, 'nombre' => 'CHIVATA', 'departamento_id' => 7],
            ['id' => 226, 'nombre' => 'CIENEGA ', 'departamento_id' => 7],
            ['id' => 227, 'nombre' => 'COMBITA', 'departamento_id' => 7],
            ['id' => 228, 'nombre' => 'COPER', 'departamento_id' => 7],
            ['id' => 229, 'nombre' => 'CORRALES ', 'departamento_id' => 7],
            ['id' => 230, 'nombre' => 'COVARACHIA', 'departamento_id' => 7],
            ['id' => 231, 'nombre' => 'CUBARA', 'departamento_id' => 7],
            ['id' => 232, 'nombre' => 'CUCAITA', 'departamento_id' => 7],
            ['id' => 233, 'nombre' => 'CUITIVA', 'departamento_id' => 7],
            ['id' => 234, 'nombre' => 'CHIQUIZA', 'departamento_id' => 7],
            ['id' => 235, 'nombre' => 'CHIVOR', 'departamento_id' => 7],
            ['id' => 236, 'nombre' => 'DUITAMA', 'departamento_id' => 7],
            ['id' => 237, 'nombre' => 'EL COCUY', 'departamento_id' => 7],
            ['id' => 238, 'nombre' => 'EL ESPINO', 'departamento_id' => 7],
            ['id' => 239, 'nombre' => 'FIRAVITOBA ', 'departamento_id' => 7],
            ['id' => 240, 'nombre' => 'FLORESTA', 'departamento_id' => 7],
            ['id' => 241, 'nombre' => 'GACHANTIVA', 'departamento_id' => 7],
            ['id' => 242, 'nombre' => 'GAMEZA', 'departamento_id' => 7],
            ['id' => 243, 'nombre' => 'GARAGOA', 'departamento_id' => 7],
            ['id' => 244, 'nombre' => 'GUACAMAYAS ', 'departamento_id' => 7],
            ['id' => 245, 'nombre' => 'GUATEQUE  ', 'departamento_id' => 7],
            ['id' => 246, 'nombre' => 'GUAYATA ', 'departamento_id' => 7],
            ['id' => 247, 'nombre' => 'GUICAN', 'departamento_id' => 7],
            ['id' => 248, 'nombre' => 'IZA', 'departamento_id' => 7],
            ['id' => 249, 'nombre' => 'JENESANO', 'departamento_id' => 7],
            ['id' => 250, 'nombre' => 'JERICO', 'departamento_id' => 7],
            ['id' => 251, 'nombre' => 'LABRANZAGRANDE', 'departamento_id' => 7],
            ['id' => 252, 'nombre' => 'LA CAPILLA', 'departamento_id' => 7],
            ['id' => 253, 'nombre' => 'LA VICTORIA ', 'departamento_id' => 7],
            ['id' => 254, 'nombre' => 'LA UVITA', 'departamento_id' => 7],
            ['id' => 255, 'nombre' => 'VILLA DE LEIVA    ', 'departamento_id' => 7],
            ['id' => 256, 'nombre' => 'MACANAL', 'departamento_id' => 7],
            ['id' => 257, 'nombre' => 'MARIPI', 'departamento_id' => 7],
            ['id' => 258, 'nombre' => 'MIRAFLORES ', 'departamento_id' => 7],
            ['id' => 259, 'nombre' => 'MONGUA ', 'departamento_id' => 7],
            ['id' => 260, 'nombre' => 'MONGUI', 'departamento_id' => 7],
            ['id' => 261, 'nombre' => 'MONIQUIRA', 'departamento_id' => 7],
            ['id' => 262, 'nombre' => 'MOTAVITA', 'departamento_id' => 7],
            ['id' => 263, 'nombre' => 'MUZO', 'departamento_id' => 7],
            ['id' => 264, 'nombre' => 'NOBSA', 'departamento_id' => 7],
            ['id' => 265, 'nombre' => 'NUEVO COLON  ', 'departamento_id' => 7],
            ['id' => 266, 'nombre' => 'OICATA', 'departamento_id' => 7],
            ['id' => 267, 'nombre' => 'OTANCHE', 'departamento_id' => 7],
            ['id' => 268, 'nombre' => 'PACHAVITA', 'departamento_id' => 7],
            ['id' => 269, 'nombre' => 'PAEZ', 'departamento_id' => 7],
            ['id' => 270, 'nombre' => 'PAIPA', 'departamento_id' => 7],
            ['id' => 271, 'nombre' => 'PAJARITO', 'departamento_id' => 7],
            ['id' => 272, 'nombre' => 'PANQUEBA ', 'departamento_id' => 7],
            ['id' => 273, 'nombre' => 'PAUNA ', 'departamento_id' => 7],
            ['id' => 274, 'nombre' => 'PAYA', 'departamento_id' => 7],
            ['id' => 275, 'nombre' => 'PAZ DEL RIO ', 'departamento_id' => 7],
            ['id' => 276, 'nombre' => 'PESCA', 'departamento_id' => 7],
            ['id' => 277, 'nombre' => 'PISBA  ', 'departamento_id' => 7],
            ['id' => 278, 'nombre' => 'PUERTO BOYACA', 'departamento_id' => 7],
            ['id' => 279, 'nombre' => 'QUIPAMA', 'departamento_id' => 7],
            ['id' => 280, 'nombre' => 'RAMIRIQUI', 'departamento_id' => 7],
            ['id' => 281, 'nombre' => 'RAQUIRA', 'departamento_id' => 7],
            ['id' => 282, 'nombre' => 'RONDON', 'departamento_id' => 7],
            ['id' => 283, 'nombre' => 'SABOYA', 'departamento_id' => 7],
            ['id' => 284, 'nombre' => 'SACHICA', 'departamento_id' => 7],
            ['id' => 285, 'nombre' => 'SAMACA ', 'departamento_id' => 7],
            ['id' => 286, 'nombre' => 'SAN EDUARDO ', 'departamento_id' => 7],
            ['id' => 287, 'nombre' => 'SAN JOSE DE PARE', 'departamento_id' => 7],
            ['id' => 288, 'nombre' => 'SAN LUIS DE GACENO', 'departamento_id' => 7],
            ['id' => 289, 'nombre' => 'SAN MATEO', 'departamento_id' => 7],
            ['id' => 290, 'nombre' => 'SAN MIGUEL DE SEMA', 'departamento_id' => 7],
            ['id' => 291, 'nombre' => 'SAN PABLO DE BORBUR', 'departamento_id' => 7],
            ['id' => 292, 'nombre' => 'SANTANA ', 'departamento_id' => 7],
            ['id' => 293, 'nombre' => 'SANTA MARIA', 'departamento_id' => 7],
            ['id' => 294, 'nombre' => 'SANTA ROSA DE VITERBO', 'departamento_id' => 7],
            ['id' => 295, 'nombre' => 'SANTA SOFIA', 'departamento_id' => 7],
            ['id' => 296, 'nombre' => 'SATIVANORTE', 'departamento_id' => 7],
            ['id' => 297, 'nombre' => 'SATIVASUR', 'departamento_id' => 7],
            ['id' => 298, 'nombre' => 'SIACHOQUE', 'departamento_id' => 7],
            ['id' => 299, 'nombre' => 'SOATA', 'departamento_id' => 7],
            ['id' => 300, 'nombre' => 'SOCOTA', 'departamento_id' => 7],
            ['id' => 301, 'nombre' => 'SOCHA', 'departamento_id' => 7],
            ['id' => 302, 'nombre' => 'SOGAMOSO', 'departamento_id' => 7],
            ['id' => 303, 'nombre' => 'SOMONDOCO  ', 'departamento_id' => 7],
            ['id' => 304, 'nombre' => 'SORA ', 'departamento_id' => 7],
            ['id' => 305, 'nombre' => 'SOTAQUIRA', 'departamento_id' => 7],
            ['id' => 306, 'nombre' => 'SORACA      ', 'departamento_id' => 7],
            ['id' => 307, 'nombre' => 'SUSACON', 'departamento_id' => 7],
            ['id' => 308, 'nombre' => 'SUTAMARCHAN', 'departamento_id' => 7],
            ['id' => 309, 'nombre' => 'SUTATENZA', 'departamento_id' => 7],
            ['id' => 310, 'nombre' => 'TASCO', 'departamento_id' => 7],
            ['id' => 311, 'nombre' => 'TENZA ', 'departamento_id' => 7],
            ['id' => 312, 'nombre' => 'TIBANA ', 'departamento_id' => 7],
            ['id' => 313, 'nombre' => 'TIBASOSA', 'departamento_id' => 7],
            ['id' => 314, 'nombre' => 'TINJACA', 'departamento_id' => 7],
            ['id' => 315, 'nombre' => 'TIPACOQUE', 'departamento_id' => 7],
            ['id' => 316, 'nombre' => 'TOCA ', 'departamento_id' => 7],
            ['id' => 317, 'nombre' => 'TOGUI', 'departamento_id' => 7],
            ['id' => 318, 'nombre' => 'TOPAGA', 'departamento_id' => 7],
            ['id' => 319, 'nombre' => 'TOTA', 'departamento_id' => 7],
            ['id' => 320, 'nombre' => 'TUNUNGUA', 'departamento_id' => 7],
            ['id' => 321, 'nombre' => 'TURMEQUE', 'departamento_id' => 7],
            ['id' => 322, 'nombre' => 'TUTA ', 'departamento_id' => 7],
            ['id' => 323, 'nombre' => 'TUTASA', 'departamento_id' => 7],
            ['id' => 324, 'nombre' => 'UMBITA ', 'departamento_id' => 7],
            ['id' => 325, 'nombre' => 'VENTAQUEMADA', 'departamento_id' => 7],
            ['id' => 326, 'nombre' => 'VIRACACHA ', 'departamento_id' => 7],
            ['id' => 327, 'nombre' => 'ZETAQUIRA', 'departamento_id' => 7],
            ['id' => 328, 'nombre' => 'MANIZALES', 'departamento_id' => 8],
            ['id' => 329, 'nombre' => 'AGUADAS ', 'departamento_id' => 8],
            ['id' => 330, 'nombre' => 'ANSERMA DE LOS CABALLEROS', 'departamento_id' => 8],
            ['id' => 331, 'nombre' => 'ARANZAZU', 'departamento_id' => 8],
            ['id' => 332, 'nombre' => 'BELALCAZAR', 'departamento_id' => 8],
            ['id' => 333, 'nombre' => 'CHINCHINA', 'departamento_id' => 8],
            ['id' => 334, 'nombre' => 'FILADELFIA', 'departamento_id' => 8],
            ['id' => 335, 'nombre' => 'LA DORADA', 'departamento_id' => 8],
            ['id' => 336, 'nombre' => 'LA MERCED', 'departamento_id' => 8],
            ['id' => 337, 'nombre' => 'MANZANARES', 'departamento_id' => 8],
            ['id' => 338, 'nombre' => 'MARMATO', 'departamento_id' => 8],
            ['id' => 339, 'nombre' => 'MARQUETALIA', 'departamento_id' => 8],
            ['id' => 340, 'nombre' => 'MARULANDA', 'departamento_id' => 8],
            ['id' => 341, 'nombre' => 'NEIRA', 'departamento_id' => 8],
            ['id' => 342, 'nombre' => 'NORCASIA', 'departamento_id' => 8],
            ['id' => 343, 'nombre' => 'PACORA', 'departamento_id' => 8],
            ['id' => 344, 'nombre' => 'PALESTINA', 'departamento_id' => 8],
            ['id' => 345, 'nombre' => 'PENSILVANIA', 'departamento_id' => 8],
            ['id' => 346, 'nombre' => 'RIOSUCIO', 'departamento_id' => 8],
            ['id' => 347, 'nombre' => 'RISARALDA', 'departamento_id' => 8],
            ['id' => 348, 'nombre' => 'SALAMINA', 'departamento_id' => 8],
            ['id' => 349, 'nombre' => 'SAMANA', 'departamento_id' => 8],
            ['id' => 350, 'nombre' => 'SAN JOSE', 'departamento_id' => 8],
            ['id' => 351, 'nombre' => 'SUPIA', 'departamento_id' => 8],
            ['id' => 352, 'nombre' => 'VICTORIA', 'departamento_id' => 8],
            ['id' => 353, 'nombre' => 'VILLAMARIA', 'departamento_id' => 8],
            ['id' => 354, 'nombre' => 'VITERBO', 'departamento_id' => 8],
            ['id' => 355, 'nombre' => 'FLORENCIA', 'departamento_id' => 9],
            ['id' => 356, 'nombre' => 'ALBANIA', 'departamento_id' => 9],
            ['id' => 357, 'nombre' => 'BELEN ANDAQUIES', 'departamento_id' => 9],
            ['id' => 358, 'nombre' => 'CARTAGENA DEL CHAIRA', 'departamento_id' => 9],
            ['id' => 359, 'nombre' => 'CURILLO', 'departamento_id' => 9],
            ['id' => 360, 'nombre' => 'EL DONCELLO', 'departamento_id' => 9],
            ['id' => 361, 'nombre' => 'EL PAUJIL     ', 'departamento_id' => 9],
            ['id' => 362, 'nombre' => 'LA MONTAÑITA', 'departamento_id' => 9],
            ['id' => 363, 'nombre' => 'MILAN', 'departamento_id' => 9],
            ['id' => 364, 'nombre' => 'MORELIA', 'departamento_id' => 9],
            ['id' => 365, 'nombre' => 'PUERTO RICO', 'departamento_id' => 9],
            ['id' => 366, 'nombre' => 'SAN JOSE DE FRAGUA', 'departamento_id' => 9],
            ['id' => 367, 'nombre' => 'SAN VICENTE DEL CAGUAN', 'departamento_id' => 9],
            ['id' => 368, 'nombre' => 'SOLANO', 'departamento_id' => 9],
            ['id' => 369, 'nombre' => 'SOLITA1', 'departamento_id' => 9],
            ['id' => 370, 'nombre' => 'VALPARAISO', 'departamento_id' => 9],
            ['id' => 371, 'nombre' => 'YOPAL', 'departamento_id' => 10],
            ['id' => 372, 'nombre' => 'AGUAZUL', 'departamento_id' => 10],
            ['id' => 373, 'nombre' => 'CHAMEZA ', 'departamento_id' => 10],
            ['id' => 374, 'nombre' => 'HATO COROZAL', 'departamento_id' => 10],
            ['id' => 375, 'nombre' => 'LA SALINA', 'departamento_id' => 10],
            ['id' => 376, 'nombre' => 'MANI', 'departamento_id' => 10],
            ['id' => 377, 'nombre' => 'MONTERREY', 'departamento_id' => 10],
            ['id' => 378, 'nombre' => 'NUNCHIA', 'departamento_id' => 10],
            ['id' => 379, 'nombre' => 'OROCUE', 'departamento_id' => 10],
            ['id' => 380, 'nombre' => 'PAZ DE ARIPORO ', 'departamento_id' => 10],
            ['id' => 381, 'nombre' => 'PORE', 'departamento_id' => 10],
            ['id' => 382, 'nombre' => 'RECETOR', 'departamento_id' => 10],
            ['id' => 383, 'nombre' => 'SABANALARGA', 'departamento_id' => 10],
            ['id' => 384, 'nombre' => 'SACAMA', 'departamento_id' => 10],
            ['id' => 385, 'nombre' => 'SAN LUIS DE PALENQUE', 'departamento_id' => 10],
            ['id' => 386, 'nombre' => 'TAMARA', 'departamento_id' => 10],
            ['id' => 387, 'nombre' => 'TAURAMENA', 'departamento_id' => 10],
            ['id' => 388, 'nombre' => 'TRINIDAD', 'departamento_id' => 10],
            ['id' => 389, 'nombre' => 'VILLANUEVA', 'departamento_id' => 10],
            ['id' => 390, 'nombre' => 'POPAYAN', 'departamento_id' => 11],
            ['id' => 391, 'nombre' => 'ALMAGUER', 'departamento_id' => 11],
            ['id' => 392, 'nombre' => 'ARGELIA', 'departamento_id' => 11],
            ['id' => 393, 'nombre' => 'BALBOA', 'departamento_id' => 11],
            ['id' => 394, 'nombre' => 'BOLIVAR', 'departamento_id' => 11],
            ['id' => 395, 'nombre' => 'BUENOS AIRES', 'departamento_id' => 11],
            ['id' => 396, 'nombre' => 'CAJIBIO', 'departamento_id' => 11],
            ['id' => 397, 'nombre' => 'CALDONO', 'departamento_id' => 11],
            ['id' => 398, 'nombre' => 'CALOTO', 'departamento_id' => 11],
            ['id' => 399, 'nombre' => 'CORINTO', 'departamento_id' => 11],
            ['id' => 400, 'nombre' => 'EL TAMBO', 'departamento_id' => 11],
            ['id' => 401, 'nombre' => 'FLORENCIA', 'departamento_id' => 11],
            ['id' => 402, 'nombre' => 'GUACHENE', 'departamento_id' => 11],
            ['id' => 403, 'nombre' => 'GUAPI', 'departamento_id' => 11],
            ['id' => 404, 'nombre' => 'INZA', 'departamento_id' => 11],
            ['id' => 405, 'nombre' => 'JAMBALO', 'departamento_id' => 11],
            ['id' => 406, 'nombre' => 'LA SIERRA', 'departamento_id' => 11],
            ['id' => 407, 'nombre' => 'LA VEGA', 'departamento_id' => 11],
            ['id' => 408, 'nombre' => 'LOPEZ DE MYCAY', 'departamento_id' => 11],
            ['id' => 409, 'nombre' => 'MERCADERES', 'departamento_id' => 11],
            ['id' => 410, 'nombre' => 'MIRANDA', 'departamento_id' => 11],
            ['id' => 411, 'nombre' => 'MORALES', 'departamento_id' => 11],
            ['id' => 412, 'nombre' => 'PADILLA', 'departamento_id' => 11],
            ['id' => 413, 'nombre' => 'PAEZ', 'departamento_id' => 11],
            ['id' => 414, 'nombre' => 'PATIA(EL BORDO)', 'departamento_id' => 11],
            ['id' => 415, 'nombre' => 'PIAMONTE1', 'departamento_id' => 11],
            ['id' => 416, 'nombre' => 'PIENDAMO    ', 'departamento_id' => 11],
            ['id' => 417, 'nombre' => 'PUERTO TEJADA', 'departamento_id' => 11],
            ['id' => 418, 'nombre' => 'PURACÉ (COCONUCO)', 'departamento_id' => 11],
            ['id' => 419, 'nombre' => 'ROSAS', 'departamento_id' => 11],
            ['id' => 420, 'nombre' => 'SAN SEBASTIAN', 'departamento_id' => 11],
            ['id' => 421, 'nombre' => 'SANTANDER DE QUILICHAO', 'departamento_id' => 11],
            ['id' => 422, 'nombre' => 'SANTA ROSA', 'departamento_id' => 11],
            ['id' => 423, 'nombre' => 'SILVIA', 'departamento_id' => 11],
            ['id' => 424, 'nombre' => 'SOTARÁ (PAISPAMBA)', 'departamento_id' => 11],
            ['id' => 425, 'nombre' => 'SUAREZ', 'departamento_id' => 11],
            ['id' => 426, 'nombre' => 'SUCRE', 'departamento_id' => 11],
            ['id' => 427, 'nombre' => 'TIMBIO', 'departamento_id' => 11],
            ['id' => 428, 'nombre' => 'TIMBIQUI', 'departamento_id' => 11],
            ['id' => 429, 'nombre' => 'TORIBIO', 'departamento_id' => 11],
            ['id' => 430, 'nombre' => 'TOTORO', 'departamento_id' => 11],
            ['id' => 431, 'nombre' => 'VILLA RICA', 'departamento_id' => 11],
            ['id' => 432, 'nombre' => 'VALLEDUPAR', 'departamento_id' => 12],
            ['id' => 433, 'nombre' => 'AGUACHICA', 'departamento_id' => 12],
            ['id' => 434, 'nombre' => 'AGUSTIN CODAZZI', 'departamento_id' => 12],
            ['id' => 435, 'nombre' => 'ASTREA', 'departamento_id' => 12],
            ['id' => 436, 'nombre' => 'BECERRIL', 'departamento_id' => 12],
            ['id' => 437, 'nombre' => 'BOSCONIA', 'departamento_id' => 12],
            ['id' => 438, 'nombre' => 'CHIMICHAGUA', 'departamento_id' => 12],
            ['id' => 439, 'nombre' => 'CHIRIGUANA', 'departamento_id' => 12],
            ['id' => 440, 'nombre' => 'CURUMANI', 'departamento_id' => 12],
            ['id' => 441, 'nombre' => 'EL COPEY', 'departamento_id' => 12],
            ['id' => 442, 'nombre' => 'EL PASO', 'departamento_id' => 12],
            ['id' => 443, 'nombre' => 'GAMARRA', 'departamento_id' => 12],
            ['id' => 444, 'nombre' => 'GONZALEZ', 'departamento_id' => 12],
            ['id' => 445, 'nombre' => 'LA GLORIA', 'departamento_id' => 12],
            ['id' => 446, 'nombre' => 'LA JAGUA IBIRICO', 'departamento_id' => 12],
            ['id' => 447, 'nombre' => 'MANAURE BALCON DEL CESAR', 'departamento_id' => 12],
            ['id' => 448, 'nombre' => 'PAILITAS', 'departamento_id' => 12],
            ['id' => 449, 'nombre' => 'PELAYA', 'departamento_id' => 12],
            ['id' => 450, 'nombre' => 'PUEBLO BELLO', 'departamento_id' => 12],
            ['id' => 451, 'nombre' => 'RIO DE ORO', 'departamento_id' => 12],
            ['id' => 452, 'nombre' => 'ROBLES (LA PAZ)', 'departamento_id' => 12],
            ['id' => 453, 'nombre' => 'SAN ALBERTO ', 'departamento_id' => 12],
            ['id' => 454, 'nombre' => 'SAN DIEGO', 'departamento_id' => 12],
            ['id' => 455, 'nombre' => 'SAN MARTIN', 'departamento_id' => 12],
            ['id' => 456, 'nombre' => 'TAMALAMEQUE', 'departamento_id' => 12],
            ['id' => 457, 'nombre' => 'QUIBDO', 'departamento_id' => 13],
            ['id' => 458, 'nombre' => 'ACANDI', 'departamento_id' => 13],
            ['id' => 459, 'nombre' => 'ALTO BAUDO (PIE DE PATO)', 'departamento_id' => 13],
            ['id' => 460, 'nombre' => 'ATRATO ', 'departamento_id' => 13],
            ['id' => 461, 'nombre' => 'BAGADO', 'departamento_id' => 13],
            ['id' => 462, 'nombre' => 'BAHIA SOLANO (MUTIS)', 'departamento_id' => 13],
            ['id' => 463, 'nombre' => 'BAJO BAUDO (PIZARRO)', 'departamento_id' => 13],
            ['id' => 464, 'nombre' => 'BOJAYA (BELLAVISTA)', 'departamento_id' => 13],
            ['id' => 465, 'nombre' => 'CANTON DE SAN PABLO', 'departamento_id' => 13],
            ['id' => 466, 'nombre' => 'CARMEN DEL DARIEN', 'departamento_id' => 13],
            ['id' => 467, 'nombre' => 'CERTEGUI', 'departamento_id' => 13],
            ['id' => 468, 'nombre' => 'CONDOTO', 'departamento_id' => 13],
            ['id' => 469, 'nombre' => 'EL CARMEN ', 'departamento_id' => 13],
            ['id' => 470, 'nombre' => 'LITORAL DEL SAN JUAN', 'departamento_id' => 13],
            ['id' => 471, 'nombre' => 'ISTMINA', 'departamento_id' => 13],
            ['id' => 472, 'nombre' => 'JURADO', 'departamento_id' => 13],
            ['id' => 473, 'nombre' => 'LLORO', 'departamento_id' => 13],
            ['id' => 474, 'nombre' => 'MEDIO ATRATO', 'departamento_id' => 13],
            ['id' => 475, 'nombre' => 'MEDIO BAUDO (BOCA DE PEPE)', 'departamento_id' => 13],
            ['id' => 476, 'nombre' => 'MEDIO SAN JUAN', 'departamento_id' => 13],
            ['id' => 477, 'nombre' => 'NOVITA', 'departamento_id' => 13],
            ['id' => 478, 'nombre' => 'NUQUI', 'departamento_id' => 13],
            ['id' => 479, 'nombre' => 'RIO IRO', 'departamento_id' => 13],
            ['id' => 480, 'nombre' => 'RIO QUITO', 'departamento_id' => 13],
            ['id' => 481, 'nombre' => 'RIOSUCIO', 'departamento_id' => 13],
            ['id' => 482, 'nombre' => 'SAN JOSE DEL PALMAR', 'departamento_id' => 13],
            ['id' => 483, 'nombre' => 'SIPI', 'departamento_id' => 13],
            ['id' => 484, 'nombre' => 'TADO', 'departamento_id' => 13],
            ['id' => 485, 'nombre' => 'UNGUIA', 'departamento_id' => 13],
            ['id' => 486, 'nombre' => 'UNION PAnombreRICANA', 'departamento_id' => 13],
            ['id' => 487, 'nombre' => 'MONTERIA     ', 'departamento_id' => 14],
            ['id' => 488, 'nombre' => 'AYAPEL', 'departamento_id' => 14],
            ['id' => 489, 'nombre' => 'BUENAVISTA', 'departamento_id' => 14],
            ['id' => 490, 'nombre' => 'CANALETE', 'departamento_id' => 14],
            ['id' => 491, 'nombre' => 'CERETE', 'departamento_id' => 14],
            ['id' => 492, 'nombre' => 'CHIMA', 'departamento_id' => 14],
            ['id' => 493, 'nombre' => 'CHINU *', 'departamento_id' => 14],
            ['id' => 494, 'nombre' => 'CIENAGA DE ORO', 'departamento_id' => 14],
            ['id' => 495, 'nombre' => 'COTORRA', 'departamento_id' => 14],
            ['id' => 496, 'nombre' => 'LA APARTADA', 'departamento_id' => 14],
            ['id' => 497, 'nombre' => 'LORICA', 'departamento_id' => 14],
            ['id' => 498, 'nombre' => 'LOS CORDOBAS', 'departamento_id' => 14],
            ['id' => 499, 'nombre' => 'MOMIL', 'departamento_id' => 14],
            ['id' => 500, 'nombre' => 'MONTELIBANO', 'departamento_id' => 14],
            ['id' => 501, 'nombre' => 'MOÑITOS', 'departamento_id' => 14],
            ['id' => 502, 'nombre' => 'PLANETA RICA', 'departamento_id' => 14],
            ['id' => 503, 'nombre' => 'PUEBLO NUEVO', 'departamento_id' => 14],
            ['id' => 504, 'nombre' => 'PUERTO ESCONDIDO', 'departamento_id' => 14],
            ['id' => 505, 'nombre' => 'PUERTO LIBERTADOR', 'departamento_id' => 14],
            ['id' => 506, 'nombre' => 'PURISIMA', 'departamento_id' => 14],
            ['id' => 507, 'nombre' => 'SAHAGUN', 'departamento_id' => 14],
            ['id' => 508, 'nombre' => 'SAN ANDRES SOTAVENTO', 'departamento_id' => 14],
            ['id' => 509, 'nombre' => 'SAN ANTERO', 'departamento_id' => 14],
            ['id' => 510, 'nombre' => 'SAN BERNARDO VIENTO ', 'departamento_id' => 14],
            ['id' => 511, 'nombre' => 'SAN CARLOS', 'departamento_id' => 14],
            ['id' => 512, 'nombre' => 'SAN JOSÉ DE URÉ *', 'departamento_id' => 14],
            ['id' => 513, 'nombre' => 'SAN PELAYO', 'departamento_id' => 14],
            ['id' => 514, 'nombre' => 'TIERRALTA', 'departamento_id' => 14],
            ['id' => 515, 'nombre' => 'TUCHÍN *', 'departamento_id' => 14],
            ['id' => 516, 'nombre' => 'VALENCIA', 'departamento_id' => 14],
            ['id' => 517, 'nombre' => 'BOGOTA D.C.', 'departamento_id' => 15],
            ['id' => 518, 'nombre' => 'AGUA DE DIOS', 'departamento_id' => 15],
            ['id' => 519, 'nombre' => 'ALBAN', 'departamento_id' => 15],
            ['id' => 520, 'nombre' => 'ANAPOIMA', 'departamento_id' => 15],
            ['id' => 521, 'nombre' => 'ANOLAIMA', 'departamento_id' => 15],
            ['id' => 522, 'nombre' => 'ARBELAEZ', 'departamento_id' => 15],
            ['id' => 523, 'nombre' => 'BELTRAN', 'departamento_id' => 15],
            ['id' => 524, 'nombre' => 'BITUIMA', 'departamento_id' => 15],
            ['id' => 525, 'nombre' => 'BOJACA', 'departamento_id' => 15],
            ['id' => 526, 'nombre' => 'CABRERA', 'departamento_id' => 15],
            ['id' => 527, 'nombre' => 'CACHIPAY', 'departamento_id' => 15],
            ['id' => 528, 'nombre' => 'CAJICA', 'departamento_id' => 15],
            ['id' => 529, 'nombre' => 'CAPARRAPI', 'departamento_id' => 15],
            ['id' => 530, 'nombre' => 'CAQUEZA', 'departamento_id' => 15],
            ['id' => 531, 'nombre' => 'CARMEN DE CARUPA', 'departamento_id' => 15],
            ['id' => 532, 'nombre' => 'CHAGUANI', 'departamento_id' => 15],
            ['id' => 533, 'nombre' => 'CHIA', 'departamento_id' => 15],
            ['id' => 534, 'nombre' => 'CHIPAQUE', 'departamento_id' => 15],
            ['id' => 535, 'nombre' => 'CHOACHI', 'departamento_id' => 15],
            ['id' => 536, 'nombre' => 'CHOCONTA', 'departamento_id' => 15],
            ['id' => 537, 'nombre' => 'COGUA', 'departamento_id' => 15],
            ['id' => 538, 'nombre' => 'COTA', 'departamento_id' => 15],
            ['id' => 539, 'nombre' => 'CUCUNUBA', 'departamento_id' => 15],
            ['id' => 540, 'nombre' => 'EL COLEGIO', 'departamento_id' => 15],
            ['id' => 541, 'nombre' => 'EL PEÑON', 'departamento_id' => 15],
            ['id' => 542, 'nombre' => 'EL ROSAL', 'departamento_id' => 15],
            ['id' => 543, 'nombre' => 'FACATATIVA', 'departamento_id' => 15],
            ['id' => 544, 'nombre' => 'FOMEQUE', 'departamento_id' => 15],
            ['id' => 545, 'nombre' => 'FOSCA', 'departamento_id' => 15],
            ['id' => 546, 'nombre' => 'FUNZA', 'departamento_id' => 15],
            ['id' => 547, 'nombre' => 'FUQUENE', 'departamento_id' => 15],
            ['id' => 548, 'nombre' => 'FUSAGASUGA  ', 'departamento_id' => 15],
            ['id' => 549, 'nombre' => 'GACHALA', 'departamento_id' => 15],
            ['id' => 550, 'nombre' => 'GACHANCIPA', 'departamento_id' => 15],
            ['id' => 551, 'nombre' => 'GACHETA', 'departamento_id' => 15],
            ['id' => 552, 'nombre' => 'GAMA', 'departamento_id' => 15],
            ['id' => 553, 'nombre' => 'GIRARDOT', 'departamento_id' => 15],
            ['id' => 554, 'nombre' => 'GRANADA', 'departamento_id' => 15],
            ['id' => 555, 'nombre' => 'GUACHETA', 'departamento_id' => 15],
            ['id' => 556, 'nombre' => 'GUADUAS', 'departamento_id' => 15],
            ['id' => 557, 'nombre' => 'GUASCA', 'departamento_id' => 15],
            ['id' => 558, 'nombre' => 'GUATAQUI', 'departamento_id' => 15],
            ['id' => 559, 'nombre' => 'GUATAVITA', 'departamento_id' => 15],
            ['id' => 560, 'nombre' => 'GUAYABAL DE SIQUIMA', 'departamento_id' => 15],
            ['id' => 561, 'nombre' => 'GUAYABETAL', 'departamento_id' => 15],
            ['id' => 562, 'nombre' => 'GUTIERREZ', 'departamento_id' => 15],
            ['id' => 563, 'nombre' => 'JERUSALEN', 'departamento_id' => 15],
            ['id' => 564, 'nombre' => 'JUNIN', 'departamento_id' => 15],
            ['id' => 565, 'nombre' => 'LA CALERA', 'departamento_id' => 15],
            ['id' => 566, 'nombre' => 'LA MESA', 'departamento_id' => 15],
            ['id' => 567, 'nombre' => 'LA PALMA', 'departamento_id' => 15],
            ['id' => 568, 'nombre' => 'LA PEÑA', 'departamento_id' => 15],
            ['id' => 569, 'nombre' => 'LA VEGA', 'departamento_id' => 15],
            ['id' => 570, 'nombre' => 'LENGUAZAQUE', 'departamento_id' => 15],
            ['id' => 571, 'nombre' => 'MACHETA', 'departamento_id' => 15],
            ['id' => 572, 'nombre' => 'MADRID', 'departamento_id' => 15],
            ['id' => 573, 'nombre' => 'MANTA', 'departamento_id' => 15],
            ['id' => 574, 'nombre' => 'MEDINA', 'departamento_id' => 15],
            ['id' => 575, 'nombre' => 'MOSQUERA', 'departamento_id' => 15],
            ['id' => 576, 'nombre' => 'NARIÑO', 'departamento_id' => 15],
            ['id' => 577, 'nombre' => 'NEMOCON', 'departamento_id' => 15],
            ['id' => 578, 'nombre' => 'NILO', 'departamento_id' => 15],
            ['id' => 579, 'nombre' => 'NIMAIMA', 'departamento_id' => 15],
            ['id' => 580, 'nombre' => 'NOCAIMA', 'departamento_id' => 15],
            ['id' => 581, 'nombre' => 'VENECIA (OSPINA PEREZ)', 'departamento_id' => 15],
            ['id' => 582, 'nombre' => 'PACHO ', 'departamento_id' => 15],
            ['id' => 583, 'nombre' => 'PAIME', 'departamento_id' => 15],
            ['id' => 584, 'nombre' => 'PANDI', 'departamento_id' => 15],
            ['id' => 585, 'nombre' => 'PARATEBUENO', 'departamento_id' => 15],
            ['id' => 586, 'nombre' => 'PASCA', 'departamento_id' => 15],
            ['id' => 587, 'nombre' => 'PUERTO SALGAR ', 'departamento_id' => 15],
            ['id' => 588, 'nombre' => 'PULI ', 'departamento_id' => 15],
            ['id' => 589, 'nombre' => 'QUEBRADANEGRA', 'departamento_id' => 15],
            ['id' => 590, 'nombre' => 'QUETAME', 'departamento_id' => 15],
            ['id' => 591, 'nombre' => 'QUIPILE', 'departamento_id' => 15],
            ['id' => 592, 'nombre' => 'APULO (RAFAEL REYES)', 'departamento_id' => 15],
            ['id' => 593, 'nombre' => 'RICAURTE', 'departamento_id' => 15],
            ['id' => 594, 'nombre' => 'SAN ANTONIO DEL TEQUENDAMA', 'departamento_id' => 15],
            ['id' => 595, 'nombre' => 'SAN BERNARDO ', 'departamento_id' => 15],
            ['id' => 596, 'nombre' => 'SAN CAYETANO', 'departamento_id' => 15],
            ['id' => 597, 'nombre' => 'SAN FRANCISCO', 'departamento_id' => 15],
            ['id' => 598, 'nombre' => 'SAN JUAN DE RIOSECO', 'departamento_id' => 15],
            ['id' => 599, 'nombre' => 'SASAIMA', 'departamento_id' => 15],
            ['id' => 600, 'nombre' => 'SESQUILE', 'departamento_id' => 15],
            ['id' => 601, 'nombre' => 'SIBATE', 'departamento_id' => 15],
            ['id' => 602, 'nombre' => 'SILVANIA', 'departamento_id' => 15],
            ['id' => 603, 'nombre' => 'SIMIJACA', 'departamento_id' => 15],
            ['id' => 604, 'nombre' => 'SOACHA', 'departamento_id' => 15],
            ['id' => 605, 'nombre' => 'SOPO', 'departamento_id' => 15],
            ['id' => 606, 'nombre' => 'SUBACHOQUE', 'departamento_id' => 15],
            ['id' => 607, 'nombre' => 'SUESCA', 'departamento_id' => 15],
            ['id' => 608, 'nombre' => 'SUPATA', 'departamento_id' => 15],
            ['id' => 609, 'nombre' => 'SUSA', 'departamento_id' => 15],
            ['id' => 610, 'nombre' => 'SUTATAUSA', 'departamento_id' => 15],
            ['id' => 611, 'nombre' => 'TABIO', 'departamento_id' => 15],
            ['id' => 612, 'nombre' => 'TAUSA', 'departamento_id' => 15],
            ['id' => 613, 'nombre' => 'TENA', 'departamento_id' => 15],
            ['id' => 614, 'nombre' => 'TENJO', 'departamento_id' => 15],
            ['id' => 615, 'nombre' => 'TIBACUY', 'departamento_id' => 15],
            ['id' => 616, 'nombre' => 'TIBIRITA', 'departamento_id' => 15],
            ['id' => 617, 'nombre' => 'TOCAIMA', 'departamento_id' => 15],
            ['id' => 618, 'nombre' => 'TOCANCIPA', 'departamento_id' => 15],
            ['id' => 619, 'nombre' => 'TOPAIPI', 'departamento_id' => 15],
            ['id' => 620, 'nombre' => 'UBALA', 'departamento_id' => 15],
            ['id' => 621, 'nombre' => 'UBAQUE', 'departamento_id' => 15],
            ['id' => 622, 'nombre' => 'UBATE', 'departamento_id' => 15],
            ['id' => 623, 'nombre' => 'UNE ', 'departamento_id' => 15],
            ['id' => 624, 'nombre' => 'UTICA', 'departamento_id' => 15],
            ['id' => 625, 'nombre' => 'VERGARA', 'departamento_id' => 15],
            ['id' => 626, 'nombre' => 'VIANI', 'departamento_id' => 15],
            ['id' => 627, 'nombre' => 'VILLAGÓMEZ', 'departamento_id' => 15],
            ['id' => 628, 'nombre' => 'VILLAPINZON      ', 'departamento_id' => 15],
            ['id' => 629, 'nombre' => 'VILLETA', 'departamento_id' => 15],
            ['id' => 630, 'nombre' => 'VIOTA', 'departamento_id' => 15],
            ['id' => 631, 'nombre' => 'YACOPI', 'departamento_id' => 15],
            ['id' => 632, 'nombre' => 'ZIPACON', 'departamento_id' => 15],
            ['id' => 633, 'nombre' => 'ZIPAQUIRA', 'departamento_id' => 15],
            ['id' => 634, 'nombre' => 'PUERTO INIRIDA', 'departamento_id' => 16],
            ['id' => 635, 'nombre' => 'BARRANCO MINAS', 'departamento_id' => 16],
            ['id' => 636, 'nombre' => 'RIOHACHA ', 'departamento_id' => 17],
            ['id' => 637, 'nombre' => 'ALBANIA ', 'departamento_id' => 17],
            ['id' => 638, 'nombre' => 'BARRANCAS ', 'departamento_id' => 17],
            ['id' => 639, 'nombre' => 'DIBULLA', 'departamento_id' => 17],
            ['id' => 640, 'nombre' => 'DISTRACCION', 'departamento_id' => 17],
            ['id' => 641, 'nombre' => 'EL MOLINO', 'departamento_id' => 17],
            ['id' => 642, 'nombre' => 'FONSECA', 'departamento_id' => 17],
            ['id' => 643, 'nombre' => 'HATONUEVO ', 'departamento_id' => 17],
            ['id' => 644, 'nombre' => 'LA JAGUA DEL PILAR', 'departamento_id' => 17],
            ['id' => 645, 'nombre' => 'MAICAO', 'departamento_id' => 17],
            ['id' => 646, 'nombre' => 'MANAURE', 'departamento_id' => 17],
            ['id' => 647, 'nombre' => 'SAN JUAN DEL CESAR ', 'departamento_id' => 17],
            ['id' => 648, 'nombre' => 'URIBIA', 'departamento_id' => 17],
            ['id' => 649, 'nombre' => 'URUMITA ', 'departamento_id' => 17],
            ['id' => 650, 'nombre' => 'VILLANUEVA', 'departamento_id' => 17],
            ['id' => 651, 'nombre' => 'SAN JOSE DEL GUAVIARE', 'departamento_id' => 18],
            ['id' => 652, 'nombre' => 'CALAMAR', 'departamento_id' => 18],
            ['id' => 653, 'nombre' => 'EL RETORNO', 'departamento_id' => 18],
            ['id' => 654, 'nombre' => 'MIRAFLORES', 'departamento_id' => 18],
            ['id' => 655, 'nombre' => 'NEIVA', 'departamento_id' => 19],
            ['id' => 656, 'nombre' => 'ACEVEDO', 'departamento_id' => 19],
            ['id' => 657, 'nombre' => 'AGRADO', 'departamento_id' => 19],
            ['id' => 658, 'nombre' => 'AIPE', 'departamento_id' => 19],
            ['id' => 659, 'nombre' => 'ALGECIRAS', 'departamento_id' => 19],
            ['id' => 660, 'nombre' => 'ALTAMIRA', 'departamento_id' => 19],
            ['id' => 661, 'nombre' => 'BARAYA', 'departamento_id' => 19],
            ['id' => 662, 'nombre' => 'CAMPOALEGRE', 'departamento_id' => 19],
            ['id' => 663, 'nombre' => 'COLOMBIA', 'departamento_id' => 19],
            ['id' => 664, 'nombre' => 'ELIAS', 'departamento_id' => 19],
            ['id' => 665, 'nombre' => 'GARZON', 'departamento_id' => 19],
            ['id' => 666, 'nombre' => 'GIGANTE', 'departamento_id' => 19],
            ['id' => 667, 'nombre' => 'GUADALUPE', 'departamento_id' => 19],
            ['id' => 668, 'nombre' => 'HOBO', 'departamento_id' => 19],
            ['id' => 669, 'nombre' => 'IQUIRA', 'departamento_id' => 19],
            ['id' => 670, 'nombre' => 'ISNOS', 'departamento_id' => 19],
            ['id' => 671, 'nombre' => 'LA ARGENTINA', 'departamento_id' => 19],
            ['id' => 672, 'nombre' => 'LA PLATA', 'departamento_id' => 19],
            ['id' => 673, 'nombre' => 'NATAGA', 'departamento_id' => 19],
            ['id' => 674, 'nombre' => 'OPORAPA', 'departamento_id' => 19],
            ['id' => 675, 'nombre' => 'PAICOL', 'departamento_id' => 19],
            ['id' => 676, 'nombre' => 'PALERMO', 'departamento_id' => 19],
            ['id' => 677, 'nombre' => 'PALESTINA', 'departamento_id' => 19],
            ['id' => 678, 'nombre' => 'PITAL', 'departamento_id' => 19],
            ['id' => 679, 'nombre' => 'PITALITO', 'departamento_id' => 19],
            ['id' => 680, 'nombre' => 'RIVERA', 'departamento_id' => 19],
            ['id' => 681, 'nombre' => 'SALADOBLANCO', 'departamento_id' => 19],
            ['id' => 682, 'nombre' => 'SAN AGUSTIN', 'departamento_id' => 19],
            ['id' => 683, 'nombre' => 'SANTA MARIA', 'departamento_id' => 19],
            ['id' => 684, 'nombre' => 'SUAZA', 'departamento_id' => 19],
            ['id' => 685, 'nombre' => 'TARQUI', 'departamento_id' => 19],
            ['id' => 686, 'nombre' => 'TESALIA', 'departamento_id' => 19],
            ['id' => 687, 'nombre' => 'TELLO', 'departamento_id' => 19],
            ['id' => 688, 'nombre' => 'TERUEL', 'departamento_id' => 19],
            ['id' => 689, 'nombre' => 'TIMANA', 'departamento_id' => 19],
            ['id' => 690, 'nombre' => 'VILLAVIEJA', 'departamento_id' => 19],
            ['id' => 691, 'nombre' => 'YAGUARA', 'departamento_id' => 19],
            ['id' => 692, 'nombre' => 'SANTA MARTA, DISTRITO TURISTICO, CULTURAL E HISTORICO', 'departamento_id' => 20],
            ['id' => 693, 'nombre' => 'ALGARROBO', 'departamento_id' => 20],
            ['id' => 694, 'nombre' => 'ARACATACA', 'departamento_id' => 20],
            ['id' => 695, 'nombre' => 'ARIGUANÍ (EL DIFÍCIL)', 'departamento_id' => 20],
            ['id' => 696, 'nombre' => 'CERRO SAN ANTONIO', 'departamento_id' => 20],
            ['id' => 697, 'nombre' => 'CHIVOLO', 'departamento_id' => 20],
            ['id' => 698, 'nombre' => 'CIENAGA  (MAGD)', 'departamento_id' => 20],
            ['id' => 699, 'nombre' => 'CONCORDIA', 'departamento_id' => 20],
            ['id' => 700, 'nombre' => 'EL BANCO', 'departamento_id' => 20],
            ['id' => 701, 'nombre' => 'EL PIÑON', 'departamento_id' => 20],
            ['id' => 702, 'nombre' => 'EL RETEN', 'departamento_id' => 20],
            ['id' => 703, 'nombre' => 'FUNDACION', 'departamento_id' => 20],
            ['id' => 704, 'nombre' => 'GUAMAL', 'departamento_id' => 20],
            ['id' => 705, 'nombre' => 'NUEVA GRANADA', 'departamento_id' => 20],
            ['id' => 706, 'nombre' => 'PEDRAZA', 'departamento_id' => 20],
            ['id' => 707, 'nombre' => 'PIJIÑO DEL CARMEN', 'departamento_id' => 20],
            ['id' => 708, 'nombre' => 'PIVIJAY', 'departamento_id' => 20],
            ['id' => 709, 'nombre' => 'PLATO ', 'departamento_id' => 20],
            ['id' => 710, 'nombre' => 'PUEBLOVIEJO', 'departamento_id' => 20],
            ['id' => 711, 'nombre' => 'REMOLINO', 'departamento_id' => 20],
            ['id' => 712, 'nombre' => 'SABANAS DE SAN ANGEL', 'departamento_id' => 20],
            ['id' => 713, 'nombre' => 'SALAMINA', 'departamento_id' => 20],
            ['id' => 714, 'nombre' => 'SAN SEBASTIAN DE BUENAVISTA', 'departamento_id' => 20],
            ['id' => 715, 'nombre' => 'SAN ZENON', 'departamento_id' => 20],
            ['id' => 716, 'nombre' => 'SANTA ANA', 'departamento_id' => 20],
            ['id' => 717, 'nombre' => 'SANTA BARBARA DE PINTO', 'departamento_id' => 20],
            ['id' => 718, 'nombre' => 'SITIONUEVO', 'departamento_id' => 20],
            ['id' => 719, 'nombre' => 'TENERIFE', 'departamento_id' => 20],
            ['id' => 720, 'nombre' => 'ZAPAYAN', 'departamento_id' => 20],
            ['id' => 721, 'nombre' => 'ZONA BANANERA', 'departamento_id' => 20],
            ['id' => 722, 'nombre' => 'VILLAVICENCIO', 'departamento_id' => 21],
            ['id' => 723, 'nombre' => 'ACACIAS', 'departamento_id' => 21],
            ['id' => 724, 'nombre' => 'BARRANCA DE UPIA', 'departamento_id' => 21],
            ['id' => 725, 'nombre' => 'CABUYARO', 'departamento_id' => 21],
            ['id' => 726, 'nombre' => 'CASTILLA LA NUEVA', 'departamento_id' => 21],
            ['id' => 727, 'nombre' => 'CUBARRAL', 'departamento_id' => 21],
            ['id' => 728, 'nombre' => 'CUMARAL', 'departamento_id' => 21],
            ['id' => 729, 'nombre' => 'EL CALVARIO', 'departamento_id' => 21],
            ['id' => 730, 'nombre' => 'EL CASTILLO', 'departamento_id' => 21],
            ['id' => 731, 'nombre' => 'EL DORADO', 'departamento_id' => 21],
            ['id' => 732, 'nombre' => 'FUENTE DE ORO', 'departamento_id' => 21],
            ['id' => 733, 'nombre' => 'GRANADA', 'departamento_id' => 21],
            ['id' => 734, 'nombre' => 'GUAMAL', 'departamento_id' => 21],
            ['id' => 735, 'nombre' => 'MAPIRIPAN', 'departamento_id' => 21],
            ['id' => 736, 'nombre' => 'MESETAS', 'departamento_id' => 21],
            ['id' => 737, 'nombre' => 'LA MACARENA', 'departamento_id' => 21],
            ['id' => 738, 'nombre' => 'LA URIBE', 'departamento_id' => 21],
            ['id' => 739, 'nombre' => 'LEJANIAS    ', 'departamento_id' => 21],
            ['id' => 740, 'nombre' => 'PUERTO CONCORDIA    ', 'departamento_id' => 21],
            ['id' => 741, 'nombre' => 'PUERTO GAITAN  ', 'departamento_id' => 21],
            ['id' => 742, 'nombre' => 'PUERTO LOPEZ', 'departamento_id' => 21],
            ['id' => 743, 'nombre' => 'PUERTO LLERAS', 'departamento_id' => 21],
            ['id' => 744, 'nombre' => 'PUERTO RICO', 'departamento_id' => 21],
            ['id' => 745, 'nombre' => 'RESTREPO', 'departamento_id' => 21],
            ['id' => 746, 'nombre' => 'SAN CARLOS GUAROA', 'departamento_id' => 21],
            ['id' => 747, 'nombre' => 'SAN JUAN DE ARAMA', 'departamento_id' => 21],
            ['id' => 748, 'nombre' => 'SAN JUANITO', 'departamento_id' => 21],
            ['id' => 749, 'nombre' => 'SAN MARTIN', 'departamento_id' => 21],
            ['id' => 750, 'nombre' => 'VISTA HERMOSA', 'departamento_id' => 21],
            ['id' => 751, 'nombre' => 'PASTO', 'departamento_id' => 22],
            ['id' => 752, 'nombre' => 'ALBAN', 'departamento_id' => 22],
            ['id' => 753, 'nombre' => 'ALDANA', 'departamento_id' => 22],
            ['id' => 754, 'nombre' => 'ANCUYA', 'departamento_id' => 22],
            ['id' => 755, 'nombre' => 'ARBOLEDA (BERRUECOS)', 'departamento_id' => 22],
            ['id' => 756, 'nombre' => 'BARBACOAS', 'departamento_id' => 22],
            ['id' => 757, 'nombre' => 'BELEN', 'departamento_id' => 22],
            ['id' => 758, 'nombre' => 'BUESACO', 'departamento_id' => 22],
            ['id' => 759, 'nombre' => 'COLON(GENOVA)', 'departamento_id' => 22],
            ['id' => 760, 'nombre' => 'CONSACA', 'departamento_id' => 22],
            ['id' => 761, 'nombre' => 'CONTADERO', 'departamento_id' => 22],
            ['id' => 762, 'nombre' => 'CORDOBA', 'departamento_id' => 22],
            ['id' => 763, 'nombre' => 'CUASPUD (CARLOSAMA)', 'departamento_id' => 22],
            ['id' => 764, 'nombre' => 'CUMBAL', 'departamento_id' => 22],
            ['id' => 765, 'nombre' => 'CUMBITARA', 'departamento_id' => 22],
            ['id' => 766, 'nombre' => 'CHACHAGUI', 'departamento_id' => 22],
            ['id' => 767, 'nombre' => 'EL CHARCO', 'departamento_id' => 22],
            ['id' => 768, 'nombre' => 'EL PEÑOL', 'departamento_id' => 22],
            ['id' => 769, 'nombre' => 'EL ROSARIO', 'departamento_id' => 22],
            ['id' => 770, 'nombre' => 'EL TABLON', 'departamento_id' => 22],
            ['id' => 771, 'nombre' => 'EL TAMBO', 'departamento_id' => 22],
            ['id' => 772, 'nombre' => 'FUNES', 'departamento_id' => 22],
            ['id' => 773, 'nombre' => 'GUACHUCAL   ', 'departamento_id' => 22],
            ['id' => 774, 'nombre' => 'GUAITARILLA    ', 'departamento_id' => 22],
            ['id' => 775, 'nombre' => 'GUALMATAN', 'departamento_id' => 22],
            ['id' => 776, 'nombre' => 'ILES', 'departamento_id' => 22],
            ['id' => 777, 'nombre' => 'IMUES', 'departamento_id' => 22],
            ['id' => 778, 'nombre' => 'IPIALES ', 'departamento_id' => 22],
            ['id' => 779, 'nombre' => 'LA CRUZ', 'departamento_id' => 22],
            ['id' => 780, 'nombre' => 'LA FLORIDA ', 'departamento_id' => 22],
            ['id' => 781, 'nombre' => 'LA LLANADA', 'departamento_id' => 22],
            ['id' => 782, 'nombre' => 'LA TOLA', 'departamento_id' => 22],
            ['id' => 783, 'nombre' => 'LA UNION    ', 'departamento_id' => 22],
            ['id' => 784, 'nombre' => 'LEIVA    ', 'departamento_id' => 22],
            ['id' => 785, 'nombre' => 'LINARES', 'departamento_id' => 22],
            ['id' => 786, 'nombre' => 'LOS ANDES', 'departamento_id' => 22],
            ['id' => 787, 'nombre' => 'MAGÜÍ (PAYÁN)', 'departamento_id' => 22],
            ['id' => 788, 'nombre' => 'MALLAMA', 'departamento_id' => 22],
            ['id' => 789, 'nombre' => 'MOSQUERA', 'departamento_id' => 22],
            ['id' => 790, 'nombre' => 'NARIÑO', 'departamento_id' => 22],
            ['id' => 791, 'nombre' => 'OLAYA HERRERA   ', 'departamento_id' => 22],
            ['id' => 792, 'nombre' => 'OSPINA', 'departamento_id' => 22],
            ['id' => 793, 'nombre' => 'FRANCISCO PIZARRO', 'departamento_id' => 22],
            ['id' => 794, 'nombre' => 'POLICARPA', 'departamento_id' => 22],
            ['id' => 795, 'nombre' => 'POTOSI ', 'departamento_id' => 22],
            ['id' => 796, 'nombre' => 'PROVIDENCIA', 'departamento_id' => 22],
            ['id' => 797, 'nombre' => 'PUERRES', 'departamento_id' => 22],
            ['id' => 798, 'nombre' => 'PUPIALES', 'departamento_id' => 22],
            ['id' => 799, 'nombre' => 'RICAURTE', 'departamento_id' => 22],
            ['id' => 800, 'nombre' => 'ROBERTO PAYAN', 'departamento_id' => 22],
            ['id' => 801, 'nombre' => 'SAMANIEGO', 'departamento_id' => 22],
            ['id' => 802, 'nombre' => 'SANDONA', 'departamento_id' => 22],
            ['id' => 803, 'nombre' => 'SAN BERNARDO', 'departamento_id' => 22],
            ['id' => 804, 'nombre' => 'SAN LORENZO', 'departamento_id' => 22],
            ['id' => 805, 'nombre' => 'SAN PABLO', 'departamento_id' => 22],
            ['id' => 806, 'nombre' => 'SAN PEDRO DE CARTAGO ', 'departamento_id' => 22],
            ['id' => 807, 'nombre' => 'SANTA BÁRBARA (ISCUANDÉ)', 'departamento_id' => 22],
            ['id' => 808, 'nombre' => 'SANTACRUZ', 'departamento_id' => 22],
            ['id' => 809, 'nombre' => 'SAPUYES', 'departamento_id' => 22],
            ['id' => 810, 'nombre' => 'TAMINANGO', 'departamento_id' => 22],
            ['id' => 811, 'nombre' => 'TANGUA', 'departamento_id' => 22],
            ['id' => 812, 'nombre' => 'TUMACO', 'departamento_id' => 22],
            ['id' => 813, 'nombre' => 'TUQUERRES', 'departamento_id' => 22],
            ['id' => 814, 'nombre' => 'YACUANQUER', 'departamento_id' => 22],
            ['id' => 815, 'nombre' => 'CUCUTA', 'departamento_id' => 23],
            ['id' => 816, 'nombre' => 'ABREGO', 'departamento_id' => 23],
            ['id' => 817, 'nombre' => 'ARBOLEDAS', 'departamento_id' => 23],
            ['id' => 818, 'nombre' => 'BOCHALEMA', 'departamento_id' => 23],
            ['id' => 819, 'nombre' => 'BUCARASICA', 'departamento_id' => 23],
            ['id' => 820, 'nombre' => 'CACOTA', 'departamento_id' => 23],
            ['id' => 821, 'nombre' => 'CACHIRA    ', 'departamento_id' => 23],
            ['id' => 822, 'nombre' => 'CHINACOTA', 'departamento_id' => 23],
            ['id' => 823, 'nombre' => 'CHITAGA    ', 'departamento_id' => 23],
            ['id' => 824, 'nombre' => 'CONVENCION', 'departamento_id' => 23],
            ['id' => 825, 'nombre' => 'CUCUTILLA', 'departamento_id' => 23],
            ['id' => 826, 'nombre' => 'DURANIA', 'departamento_id' => 23],
            ['id' => 827, 'nombre' => 'EL CARMEN', 'departamento_id' => 23],
            ['id' => 828, 'nombre' => 'EL TARRA', 'departamento_id' => 23],
            ['id' => 829, 'nombre' => 'EL ZULIA', 'departamento_id' => 23],
            ['id' => 830, 'nombre' => 'GRAMALOTE', 'departamento_id' => 23],
            ['id' => 831, 'nombre' => 'HACARI', 'departamento_id' => 23],
            ['id' => 832, 'nombre' => 'HERRAN', 'departamento_id' => 23],
            ['id' => 833, 'nombre' => 'LABATECA', 'departamento_id' => 23],
            ['id' => 834, 'nombre' => 'LA ESPERANZA ', 'departamento_id' => 23],
            ['id' => 835, 'nombre' => 'LA PLAYA', 'departamento_id' => 23],
            ['id' => 836, 'nombre' => 'LOS PATIOS', 'departamento_id' => 23],
            ['id' => 837, 'nombre' => 'LOURDES', 'departamento_id' => 23],
            ['id' => 838, 'nombre' => 'MUTISCUA', 'departamento_id' => 23],
            ['id' => 839, 'nombre' => 'OCAÑA', 'departamento_id' => 23],
            ['id' => 840, 'nombre' => 'PAMPLONA', 'departamento_id' => 23],
            ['id' => 841, 'nombre' => 'PAMPLONITA     ', 'departamento_id' => 23],
            ['id' => 842, 'nombre' => 'PUERTO SANTANDER', 'departamento_id' => 23],
            ['id' => 843, 'nombre' => 'RAGONVALIA', 'departamento_id' => 23],
            ['id' => 844, 'nombre' => 'SALAZAR ', 'departamento_id' => 23],
            ['id' => 845, 'nombre' => 'SAN CALIXTO', 'departamento_id' => 23],
            ['id' => 846, 'nombre' => 'SAN CAYETANO', 'departamento_id' => 23],
            ['id' => 847, 'nombre' => 'SANTIAGO', 'departamento_id' => 23],
            ['id' => 848, 'nombre' => 'SARDINATA', 'departamento_id' => 23],
            ['id' => 849, 'nombre' => 'SILOS', 'departamento_id' => 23],
            ['id' => 850, 'nombre' => 'TEORAMA', 'departamento_id' => 23],
            ['id' => 851, 'nombre' => 'TIBU', 'departamento_id' => 23],
            ['id' => 852, 'nombre' => 'TOLEDO', 'departamento_id' => 23],
            ['id' => 853, 'nombre' => 'VILLACARO', 'departamento_id' => 23],
            ['id' => 854, 'nombre' => 'VILLA DEL ROSARIO', 'departamento_id' => 23],
            ['id' => 855, 'nombre' => 'MOCOA', 'departamento_id' => 24],
            ['id' => 856, 'nombre' => 'COLON', 'departamento_id' => 24],
            ['id' => 857, 'nombre' => 'ORITO', 'departamento_id' => 24],
            ['id' => 858, 'nombre' => 'PUERTO ASIS     ', 'departamento_id' => 24],
            ['id' => 859, 'nombre' => 'PUERTO CAICEDO', 'departamento_id' => 24],
            ['id' => 860, 'nombre' => 'PUERTO GUZMAN', 'departamento_id' => 24],
            ['id' => 861, 'nombre' => 'PUERTO LEGUIZAMO ', 'departamento_id' => 24],
            ['id' => 862, 'nombre' => 'SIBUNDOY', 'departamento_id' => 24],
            ['id' => 863, 'nombre' => 'SAN FRANCISCO      ', 'departamento_id' => 24],
            ['id' => 864, 'nombre' => 'SAN MIGUEL', 'departamento_id' => 24],
            ['id' => 865, 'nombre' => 'SANTIAGO', 'departamento_id' => 24],
            ['id' => 866, 'nombre' => 'VALLE DEL GUAMUEZ', 'departamento_id' => 24],
            ['id' => 867, 'nombre' => 'VILLAGARZON', 'departamento_id' => 24],
            ['id' => 868, 'nombre' => 'ARMENIA', 'departamento_id' => 25],
            ['id' => 869, 'nombre' => 'BUENAVISTA ', 'departamento_id' => 25],
            ['id' => 870, 'nombre' => 'CALARCA', 'departamento_id' => 25],
            ['id' => 871, 'nombre' => 'CIRCASIA', 'departamento_id' => 25],
            ['id' => 872, 'nombre' => 'CORDOBA', 'departamento_id' => 25],
            ['id' => 873, 'nombre' => 'FILANDIA', 'departamento_id' => 25],
            ['id' => 874, 'nombre' => 'GENOVA', 'departamento_id' => 25],
            ['id' => 875, 'nombre' => 'LA TEBAIDA', 'departamento_id' => 25],
            ['id' => 876, 'nombre' => 'MONTENEGRO', 'departamento_id' => 25],
            ['id' => 877, 'nombre' => 'PIJAO', 'departamento_id' => 25],
            ['id' => 878, 'nombre' => 'QUIMBAYA', 'departamento_id' => 25],
            ['id' => 879, 'nombre' => 'SALENTO', 'departamento_id' => 25],
            ['id' => 880, 'nombre' => 'PEREIRA', 'departamento_id' => 26],
            ['id' => 881, 'nombre' => 'APIA', 'departamento_id' => 26],
            ['id' => 882, 'nombre' => 'BALBOA', 'departamento_id' => 26],
            ['id' => 883, 'nombre' => 'BELEN DE UMBRIA', 'departamento_id' => 26],
            ['id' => 884, 'nombre' => 'DOSQUEBRADAS', 'departamento_id' => 26],
            ['id' => 885, 'nombre' => 'GUATICA', 'departamento_id' => 26],
            ['id' => 886, 'nombre' => 'LA CELIA', 'departamento_id' => 26],
            ['id' => 887, 'nombre' => 'LA VIRGINIA', 'departamento_id' => 26],
            ['id' => 888, 'nombre' => 'MARSELLA', 'departamento_id' => 26],
            ['id' => 889, 'nombre' => 'MISTRATO', 'departamento_id' => 26],
            ['id' => 890, 'nombre' => 'PUEBLO RICO', 'departamento_id' => 26],
            ['id' => 891, 'nombre' => 'QUINCHIA', 'departamento_id' => 26],
            ['id' => 892, 'nombre' => 'SANTA ROSA DE CABAL', 'departamento_id' => 26],
            ['id' => 893, 'nombre' => 'SANTUARIO', 'departamento_id' => 26],
            ['id' => 894, 'nombre' => 'BUCARAMANGA', 'departamento_id' => 27],
            ['id' => 895, 'nombre' => 'AGUADA', 'departamento_id' => 27],
            ['id' => 896, 'nombre' => 'ALBANIA', 'departamento_id' => 27],
            ['id' => 897, 'nombre' => 'ARATOCA ', 'departamento_id' => 27],
            ['id' => 898, 'nombre' => 'BARBOSA', 'departamento_id' => 27],
            ['id' => 899, 'nombre' => 'BARICHARA', 'departamento_id' => 27],
            ['id' => 900, 'nombre' => 'BARRANCABERMEJA    ', 'departamento_id' => 27],
            ['id' => 901, 'nombre' => 'BETULIA ', 'departamento_id' => 27],
            ['id' => 902, 'nombre' => 'BOLIVAR ', 'departamento_id' => 27],
            ['id' => 903, 'nombre' => 'CABRERA ', 'departamento_id' => 27],
            ['id' => 904, 'nombre' => 'CALIFORNIA', 'departamento_id' => 27],
            ['id' => 905, 'nombre' => 'CAPITANEJO', 'departamento_id' => 27],
            ['id' => 906, 'nombre' => 'CARCASI    ', 'departamento_id' => 27],
            ['id' => 907, 'nombre' => 'CEPITA   ', 'departamento_id' => 27],
            ['id' => 908, 'nombre' => 'CERRITO', 'departamento_id' => 27],
            ['id' => 909, 'nombre' => 'CHARALA', 'departamento_id' => 27],
            ['id' => 910, 'nombre' => 'CHARTA', 'departamento_id' => 27],
            ['id' => 911, 'nombre' => 'CHIMA', 'departamento_id' => 27],
            ['id' => 912, 'nombre' => 'CHIPATA', 'departamento_id' => 27],
            ['id' => 913, 'nombre' => 'CIMITARRA', 'departamento_id' => 27],
            ['id' => 914, 'nombre' => 'CONCEPCION', 'departamento_id' => 27],
            ['id' => 915, 'nombre' => 'CONFINES ', 'departamento_id' => 27],
            ['id' => 916, 'nombre' => 'CONTRATACION', 'departamento_id' => 27],
            ['id' => 917, 'nombre' => 'COROMORO', 'departamento_id' => 27],
            ['id' => 918, 'nombre' => 'CURITI', 'departamento_id' => 27],
            ['id' => 919, 'nombre' => 'EL CARMEN', 'departamento_id' => 27],
            ['id' => 920, 'nombre' => 'EL GUACAMAYO ', 'departamento_id' => 27],
            ['id' => 921, 'nombre' => 'EL PEÑON', 'departamento_id' => 27],
            ['id' => 922, 'nombre' => 'EL PLAYON', 'departamento_id' => 27],
            ['id' => 923, 'nombre' => 'ENCINO', 'departamento_id' => 27],
            ['id' => 924, 'nombre' => 'ENCISO', 'departamento_id' => 27],
            ['id' => 925, 'nombre' => 'FLORIAN', 'departamento_id' => 27],
            ['id' => 926, 'nombre' => 'FLORIDABLANCA ', 'departamento_id' => 27],
            ['id' => 927, 'nombre' => 'GALAN', 'departamento_id' => 27],
            ['id' => 928, 'nombre' => 'GAMBITA', 'departamento_id' => 27],
            ['id' => 929, 'nombre' => 'GIRON ', 'departamento_id' => 27],
            ['id' => 930, 'nombre' => 'GUACA', 'departamento_id' => 27],
            ['id' => 931, 'nombre' => 'GUADALUPE', 'departamento_id' => 27],
            ['id' => 932, 'nombre' => 'GUAPOTA', 'departamento_id' => 27],
            ['id' => 933, 'nombre' => 'GUAVATA', 'departamento_id' => 27],
            ['id' => 934, 'nombre' => 'GÜEPSA', 'departamento_id' => 27],
            ['id' => 935, 'nombre' => 'HATO', 'departamento_id' => 27],
            ['id' => 936, 'nombre' => 'JESUS MARIA', 'departamento_id' => 27],
            ['id' => 937, 'nombre' => 'JORDAN', 'departamento_id' => 27],
            ['id' => 938, 'nombre' => 'LA BELLEZA', 'departamento_id' => 27],
            ['id' => 939, 'nombre' => 'LANDAZURI', 'departamento_id' => 27],
            ['id' => 940, 'nombre' => 'LA PAZ', 'departamento_id' => 27],
            ['id' => 941, 'nombre' => 'LEBRIJA ', 'departamento_id' => 27],
            ['id' => 942, 'nombre' => 'LOS SANTOS', 'departamento_id' => 27],
            ['id' => 943, 'nombre' => 'MACARAVITA', 'departamento_id' => 27],
            ['id' => 944, 'nombre' => 'MALAGA ', 'departamento_id' => 27],
            ['id' => 945, 'nombre' => 'MATANZA', 'departamento_id' => 27],
            ['id' => 946, 'nombre' => 'MOGOTES', 'departamento_id' => 27],
            ['id' => 947, 'nombre' => 'MOLAGAVITA     ', 'departamento_id' => 27],
            ['id' => 948, 'nombre' => 'OCAMONTE', 'departamento_id' => 27],
            ['id' => 949, 'nombre' => 'OIBA', 'departamento_id' => 27],
            ['id' => 950, 'nombre' => 'ONZAGA', 'departamento_id' => 27],
            ['id' => 951, 'nombre' => 'PALMAR', 'departamento_id' => 27],
            ['id' => 952, 'nombre' => 'PALMAS DEL SOCORRO', 'departamento_id' => 27],
            ['id' => 953, 'nombre' => 'PARAMO', 'departamento_id' => 27],
            ['id' => 954, 'nombre' => 'PIEDECUESTA', 'departamento_id' => 27],
            ['id' => 955, 'nombre' => 'PINCHOTE', 'departamento_id' => 27],
            ['id' => 956, 'nombre' => 'PUENTE NACIONAL', 'departamento_id' => 27],
            ['id' => 957, 'nombre' => 'PUERTO PARRA', 'departamento_id' => 27],
            ['id' => 958, 'nombre' => 'PUERTO WILCHES', 'departamento_id' => 27],
            ['id' => 959, 'nombre' => 'RIONEGRO', 'departamento_id' => 27],
            ['id' => 960, 'nombre' => 'SABANA DE TORRES    ', 'departamento_id' => 27],
            ['id' => 961, 'nombre' => 'SAN ANDRES ', 'departamento_id' => 27],
            ['id' => 962, 'nombre' => 'SAN BENITO ', 'departamento_id' => 27],
            ['id' => 963, 'nombre' => 'SAN GIL', 'departamento_id' => 27],
            ['id' => 964, 'nombre' => 'SAN JOAQUIN', 'departamento_id' => 27],
            ['id' => 965, 'nombre' => 'SAN JOSE DE MIRANDA', 'departamento_id' => 27],
            ['id' => 966, 'nombre' => 'SAN MIGUEL ', 'departamento_id' => 27],
            ['id' => 967, 'nombre' => 'SAN VICENTE DE CHUCURI', 'departamento_id' => 27],
            ['id' => 968, 'nombre' => 'SANTA BARBARA', 'departamento_id' => 27],
            ['id' => 969, 'nombre' => 'SANTA HELENA DEL OPÓN', 'departamento_id' => 27],
            ['id' => 970, 'nombre' => 'SIMACOTA', 'departamento_id' => 27],
            ['id' => 971, 'nombre' => 'SOCORRO     ', 'departamento_id' => 27],
            ['id' => 972, 'nombre' => 'SUAITA', 'departamento_id' => 27],
            ['id' => 973, 'nombre' => 'SUCRE', 'departamento_id' => 27],
            ['id' => 974, 'nombre' => 'SURATA', 'departamento_id' => 27],
            ['id' => 975, 'nombre' => 'TONA    ', 'departamento_id' => 27],
            ['id' => 976, 'nombre' => 'VALLE SAN JOSE     ', 'departamento_id' => 27],
            ['id' => 977, 'nombre' => 'VELEZ', 'departamento_id' => 27],
            ['id' => 978, 'nombre' => 'VETAS', 'departamento_id' => 27],
            ['id' => 979, 'nombre' => 'VILLANUEVA', 'departamento_id' => 27],
            ['id' => 980, 'nombre' => 'ZAPATOCA', 'departamento_id' => 27],
            ['id' => 981, 'nombre' => 'SINCELEJO', 'departamento_id' => 28],
            ['id' => 982, 'nombre' => 'BUENAVISTA', 'departamento_id' => 28],
            ['id' => 983, 'nombre' => 'CAIMITO', 'departamento_id' => 28],
            ['id' => 984, 'nombre' => 'COLOSO', 'departamento_id' => 28],
            ['id' => 985, 'nombre' => 'COROZAL', 'departamento_id' => 28],
            ['id' => 986, 'nombre' => 'COVEÑAS', 'departamento_id' => 28],
            ['id' => 987, 'nombre' => 'CHALAN', 'departamento_id' => 28],
            ['id' => 988, 'nombre' => 'EL ROBLE', 'departamento_id' => 28],
            ['id' => 989, 'nombre' => 'GALERAS', 'departamento_id' => 28],
            ['id' => 990, 'nombre' => 'GUARANDA', 'departamento_id' => 28],
            ['id' => 991, 'nombre' => 'LA UNION   ', 'departamento_id' => 28],
            ['id' => 992, 'nombre' => 'LOS PALMITOS', 'departamento_id' => 28],
            ['id' => 993, 'nombre' => 'MAJAGUAL', 'departamento_id' => 28],
            ['id' => 994, 'nombre' => 'MORROA', 'departamento_id' => 28],
            ['id' => 995, 'nombre' => 'OVEJAS', 'departamento_id' => 28],
            ['id' => 996, 'nombre' => 'SAN ANTONIO DE PALMITO', 'departamento_id' => 28],
            ['id' => 997, 'nombre' => 'SAMPUES', 'departamento_id' => 28],
            ['id' => 998, 'nombre' => 'SAN BENITO ABAD       ', 'departamento_id' => 28],
            ['id' => 999, 'nombre' => 'SAN JUAN DE BETULIA', 'departamento_id' => 28],
            ['id' => 1000, 'nombre' => 'SAN MARCOS', 'departamento_id' => 28],
            ['id' => 1001, 'nombre' => 'SAN ONOFRE', 'departamento_id' => 28],
            ['id' => 1002, 'nombre' => 'SAN PEDRO', 'departamento_id' => 28],
            ['id' => 1003, 'nombre' => 'SINCE', 'departamento_id' => 28],
            ['id' => 1004, 'nombre' => 'SUCRE', 'departamento_id' => 28],
            ['id' => 1005, 'nombre' => 'TOLU', 'departamento_id' => 28],
            ['id' => 1006, 'nombre' => 'TOLUVIEJO', 'departamento_id' => 28],
            ['id' => 1007, 'nombre' => 'IBAGUE', 'departamento_id' => 29],
            ['id' => 1008, 'nombre' => 'ALPUJARRA', 'departamento_id' => 29],
            ['id' => 1009, 'nombre' => 'ALVARADO', 'departamento_id' => 29],
            ['id' => 1010, 'nombre' => 'AMBALEMA', 'departamento_id' => 29],
            ['id' => 1011, 'nombre' => 'ANZOATEGUI', 'departamento_id' => 29],
            ['id' => 1012, 'nombre' => 'ARMERO (GUAYABAL)', 'departamento_id' => 29],
            ['id' => 1013, 'nombre' => 'ATACO', 'departamento_id' => 29],
            ['id' => 1014, 'nombre' => 'CAJAMARCA', 'departamento_id' => 29],
            ['id' => 1015, 'nombre' => 'CARMEN APICALA', 'departamento_id' => 29],
            ['id' => 1016, 'nombre' => 'CASABIANCA', 'departamento_id' => 29],
            ['id' => 1017, 'nombre' => 'CHAPARRAL', 'departamento_id' => 29],
            ['id' => 1018, 'nombre' => 'COELLO', 'departamento_id' => 29],
            ['id' => 1019, 'nombre' => 'COYAIMA ', 'departamento_id' => 29],
            ['id' => 1020, 'nombre' => 'CUNDAY', 'departamento_id' => 29],
            ['id' => 1021, 'nombre' => 'DOLORES', 'departamento_id' => 29],
            ['id' => 1022, 'nombre' => 'ESPINAL', 'departamento_id' => 29],
            ['id' => 1023, 'nombre' => 'FALAN', 'departamento_id' => 29],
            ['id' => 1024, 'nombre' => 'FLANDES', 'departamento_id' => 29],
            ['id' => 1025, 'nombre' => 'FRESNO', 'departamento_id' => 29],
            ['id' => 1026, 'nombre' => 'GUAMO', 'departamento_id' => 29],
            ['id' => 1027, 'nombre' => 'HERVEO', 'departamento_id' => 29],
            ['id' => 1028, 'nombre' => 'HONDA', 'departamento_id' => 29],
            ['id' => 1029, 'nombre' => 'ICONONZO', 'departamento_id' => 29],
            ['id' => 1030, 'nombre' => 'LERIDA', 'departamento_id' => 29],
            ['id' => 1031, 'nombre' => 'LIBANO', 'departamento_id' => 29],
            ['id' => 1032, 'nombre' => 'MARIQUITA', 'departamento_id' => 29],
            ['id' => 1033, 'nombre' => 'MELGAR', 'departamento_id' => 29],
            ['id' => 1034, 'nombre' => 'MURILLO', 'departamento_id' => 29],
            ['id' => 1035, 'nombre' => 'NATAGAIMA', 'departamento_id' => 29],
            ['id' => 1036, 'nombre' => 'ORTEGA', 'departamento_id' => 29],
            ['id' => 1037, 'nombre' => 'PALOCABILDO', 'departamento_id' => 29],
            ['id' => 1038, 'nombre' => 'PIEDRAS', 'departamento_id' => 29],
            ['id' => 1039, 'nombre' => 'PLANADAS', 'departamento_id' => 29],
            ['id' => 1040, 'nombre' => 'PRADO', 'departamento_id' => 29],
            ['id' => 1041, 'nombre' => 'PURIFICACION', 'departamento_id' => 29],
            ['id' => 1042, 'nombre' => 'RIOBLANCO', 'departamento_id' => 29],
            ['id' => 1043, 'nombre' => 'RONCESVALLES', 'departamento_id' => 29],
            ['id' => 1044, 'nombre' => 'ROVIRA', 'departamento_id' => 29],
            ['id' => 1045, 'nombre' => 'SALDAÑA', 'departamento_id' => 29],
            ['id' => 1046, 'nombre' => 'SAN ANTONIO', 'departamento_id' => 29],
            ['id' => 1047, 'nombre' => 'SAN LUIS', 'departamento_id' => 29],
            ['id' => 1048, 'nombre' => 'SANTA ISABEL', 'departamento_id' => 29],
            ['id' => 1049, 'nombre' => 'SUAREZ', 'departamento_id' => 29],
            ['id' => 1050, 'nombre' => 'VALLE DE SAN JUAN', 'departamento_id' => 29],
            ['id' => 1051, 'nombre' => 'VENADILLO', 'departamento_id' => 29],
            ['id' => 1052, 'nombre' => 'VILLAHERMOSA', 'departamento_id' => 29],
            ['id' => 1053, 'nombre' => 'VILLARRICA', 'departamento_id' => 29],
            ['id' => 1054, 'nombre' => 'CALI', 'departamento_id' => 30],
            ['id' => 1055, 'nombre' => 'ALCALA', 'departamento_id' => 30],
            ['id' => 1056, 'nombre' => 'ANDALUCIA', 'departamento_id' => 30],
            ['id' => 1057, 'nombre' => 'ANSERMANUEVO', 'departamento_id' => 30],
            ['id' => 1058, 'nombre' => 'ARGELIA', 'departamento_id' => 30],
            ['id' => 1059, 'nombre' => 'BOLIVAR', 'departamento_id' => 30],
            ['id' => 1060, 'nombre' => 'BUENAVENTURA', 'departamento_id' => 30],
            ['id' => 1061, 'nombre' => 'BUGA   ', 'departamento_id' => 30],
            ['id' => 1062, 'nombre' => 'BUGALAGRANDE', 'departamento_id' => 30],
            ['id' => 1063, 'nombre' => 'CAICEDONIA ', 'departamento_id' => 30],
            ['id' => 1064, 'nombre' => 'CALIMA DEL DARIEN', 'departamento_id' => 30],
            ['id' => 1065, 'nombre' => 'CANDELARIA ', 'departamento_id' => 30],
            ['id' => 1066, 'nombre' => 'CARTAGO', 'departamento_id' => 30],
            ['id' => 1067, 'nombre' => 'DAGUA', 'departamento_id' => 30],
            ['id' => 1068, 'nombre' => 'EL AGUILA ', 'departamento_id' => 30],
            ['id' => 1069, 'nombre' => 'EL CAIRO', 'departamento_id' => 30],
            ['id' => 1070, 'nombre' => 'EL CERRITO', 'departamento_id' => 30],
            ['id' => 1071, 'nombre' => 'EL DOVIO', 'departamento_id' => 30],
            ['id' => 1072, 'nombre' => 'FLORIDA', 'departamento_id' => 30],
            ['id' => 1073, 'nombre' => 'GINEBRA', 'departamento_id' => 30],
            ['id' => 1074, 'nombre' => 'GUACARI', 'departamento_id' => 30],
            ['id' => 1075, 'nombre' => 'JAMUNDI ', 'departamento_id' => 30],
            ['id' => 1076, 'nombre' => 'LA CUMBRE', 'departamento_id' => 30],
            ['id' => 1077, 'nombre' => 'LA UNION', 'departamento_id' => 30],
            ['id' => 1078, 'nombre' => 'LA VICTORIA', 'departamento_id' => 30],
            ['id' => 1079, 'nombre' => 'OBANDO', 'departamento_id' => 30],
            ['id' => 1080, 'nombre' => 'PALMIRA', 'departamento_id' => 30],
            ['id' => 1081, 'nombre' => 'PRADERA', 'departamento_id' => 30],
            ['id' => 1082, 'nombre' => 'RESTREPO', 'departamento_id' => 30],
            ['id' => 1083, 'nombre' => 'RIOFRIO', 'departamento_id' => 30],
            ['id' => 1084, 'nombre' => 'ROLDANILLO', 'departamento_id' => 30],
            ['id' => 1085, 'nombre' => 'SAN PEDRO', 'departamento_id' => 30],
            ['id' => 1086, 'nombre' => 'SEVILLA', 'departamento_id' => 30],
            ['id' => 1087, 'nombre' => 'TORO', 'departamento_id' => 30],
            ['id' => 1088, 'nombre' => 'TRUJILLO', 'departamento_id' => 30],
            ['id' => 1089, 'nombre' => 'TULUA ', 'departamento_id' => 30],
            ['id' => 1090, 'nombre' => 'ULLOA', 'departamento_id' => 30],
            ['id' => 1091, 'nombre' => 'VERSALLES', 'departamento_id' => 30],
            ['id' => 1092, 'nombre' => 'VIJES', 'departamento_id' => 30],
            ['id' => 1093, 'nombre' => 'YOTOCO', 'departamento_id' => 30],
            ['id' => 1094, 'nombre' => 'YUMBO', 'departamento_id' => 30],
            ['id' => 1095, 'nombre' => 'ZARZAL', 'departamento_id' => 30],
            ['id' => 1096, 'nombre' => 'MITU ', 'departamento_id' => 31],
            ['id' => 1097, 'nombre' => 'CARURU', 'departamento_id' => 31],
            ['id' => 1098, 'nombre' => 'TARAIRA', 'departamento_id' => 31],
            ['id' => 1099, 'nombre' => 'PUERTO CARREÑO', 'departamento_id' => 32],
            ['id' => 1100, 'nombre' => 'LA PRIMAVERA', 'departamento_id' => 32],
            ['id' => 1101, 'nombre' => 'SANTA ROSALIA', 'departamento_id' => 32],
            ['id' => 1102, 'nombre' => 'CUMARIBO', 'departamento_id' => 32]
        ];

        Municipio::insert($data);
    }
}
